### ISSUE TITLE
unable to call ext service workflow from CAP Service

### ISSUE THREAD

**Issue by SnarkWay** [SAP/cloud-sdk-js#1051]
Hello everyone,

I am currently facing the same issue as Mr. Jason Scott --> https://answers.sap.com/questions/13195320/unable-to-call-external-service-sap-workflow-servi.html

I want to initiate a workflow instance from my CAP Application in Business Application Studio as shown below and receive the following errors

![call workflow instance_v2](https://user-images.githubusercontent.com/15323595/109277381-8c65e100-7817-11eb-8c8f-a0bb04f3ea9c.JPG)

also without /oauth/token in Token URL I receive the error below
![Workflow-Destination_v2](https://user-images.githubusercontent.com/15323595/109277560-c931d800-7817-11eb-9687-d54168af89f5.JPG)

![package json_v2](https://user-images.githubusercontent.com/15323595/109277788-10b86400-7818-11eb-9909-9a9a1fe0bd06.JPG)

failed to load destination & access token missing:

![error_comsole_workflow_desitnation](https://user-images.githubusercontent.com/15323595/109277860-2af24200-7818-11eb-82fe-d6bc73e27596.JPG)

Do you have any solution approach for that?

Best Regards
Max

**Comment by FrankEssenberger** [comment]
Hello @SnarkWay,

just to gather some more information. Is this problem appearing when you run locally within BAS or in the deployed application? 

If you are running within the local BAS you have to make sure the VCAP_SERVICE variables are there.
Also could you try to make a reading call to see if this is working.

Best
Frank

**Comment by SnarkWay** [comment]
Hell @FrankEssenberger 

this appears by running locally. in deployed mode the error is as follows:

Uncaught (in promise) Error: 502 Bad Gateway: Registered endpoint failed to handle the request.

How can I get the VCAP_SERVICE variables?

Best Regards
Max

**Comment by FrankEssenberger** [comment]
The SDK should take care of the tokens - no action needed.

Let's focus first on getting it running locally. Because this has better dev speed. You can either use the build in functionality in BAS to get the VCAP variables -> on the left hand side there is a little cloud foundry icon there you can connect to a space and than bind the services. 

Or you just copy the content from the VCAP_VARIABLES when your app is deployed and use e.g. `.env` to set the value to the process.env. Both has the same effect. Once this is done correctly you should get rid of the `destination service instance not there` error.

Then if you keep experiencing 502 error, could you try to do a read request instead of POST. I am currently investigating and other issue regarding CSRF token fetching and it could be that this is an additional problem.

NOTE: When you run locally in the BAS you can not use destinations using OAtuh flows which are based on a JWT issued by the XSUAA for a particular user, because you have not done the auth roundtrip of login to the IdP got a token etc. Your ClientCredentials flow should be fine though.

**Comment by SnarkWay** [comment]
thanks for the hint - I bound the destination instance ('veranstaltung_workflow') to my app in the srv folder but I am experiencing the 502 error even with changing the post to a read request:

bound instance env file:


[2021-02-26T16:53:59.835Z | ERROR | 1090521]: { ErrorWithCause: Failed to build HTTP request for destination: failed to load destination!
    at new ErrorWithCause (/home/user/projects/li6a/infoboerse/node_modules/@sap-cloud-sdk/util/dist/error-with-cause.js:31:16)
    at /home/user/projects/li6a/infoboerse/node_modules/@sap-cloud-sdk/core/dist/http-client/http-client.js:199:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
Caused by:
Error: Unable to get access token for "destination" service! No service instance of type "destination" found.
    at Object.resolveService (/home/user/projects/li6a/infoboerse/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/environment-accessor.js:219:19)
    at Object.<anonymous> (/home/user/projects/li6a/infoboerse/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/token-accessor.js:73:54)
    at step (/home/user/projects/li6a/infoboerse/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/token-accessor.js:44:23)
    at Object.next (/home/user/projects/li6a/infoboerse/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/token-accessor.js:25:53)
    at /home/user/projects/li6a/infoboerse/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/token-accessor.js:19:71
    at new Promise (<anonymous>)

**Comment by SnarkWay** [comment]
is it possible that the on.'SAVE'.. method does not know how to consume that tx(req).post request? as it provokes a HTTP batch request within the CAP application..?

**Comment by SnarkWay** [comment]
I got it working. I had to to use /oauth/token in Token URL of destination plus add the WORKFLOW_INSTANCE_START functionality to my workflow service instance

**Comment by FrankEssenberger** [comment]
good to hear that it worked. Did you find the missing configuration step on your own e.g. `add the WORKFLOW_INSTANCE_START functionality to my workflow service instance` or did you find it in some documentation on the workflow service? If so I would like to link the docs here so that other people find it quicker.

**Comment by SnarkWay** [comment]
Hi Frank,

I found here the commands how to add these authorities:
https://github.com/SAP-samples/cloud-platform-workflow-virtual-event/tree/master/exercises/06

e.g. cf update-service default_workflow -c '{"authorities": ["WORKFLOW_DEFINITION_GET", "WORKFLOW_INSTANCE_START"]}'

Now that leads to another question:
do you know how to retrieve back the information from a workflow instance in a (CAP) application?
I suppose to use the API GET /v1/workflow-instances/{workflowInstanceId}/context frome here https://api.sap.com/api/SAP_CP_Workflow_CF/resource

Therefore I would need to retrieve the WorkflowInstanceId of the previosuly created Workflow from API POST /v1/workflow-instances. This API returns the id of the created workflow in the HTTP response. The question is how i can get that id from the response inside my javaScript coding. Do you know that?

Best Regards
Max

**Comment by FrankEssenberger** [comment]
Thanks for sharing the information here.

Regarding you question I would recommend you contact the CAP colleagues. 

Alternatively you can also create a API client using the [openapi client](https://sap.github.io/cloud-sdk/docs/js/features/openapi/generate-openapi-client) or you wait a bit since we will also release a client like we did for the S/4 system on npm. Then you would use the client instead of the `tx().post()`. The clients are closer to the actual HTTP calls and you should get the response as in the API spec. 

If it is ok I would close the issue?
