### ISSUE TITLE
Resolve navigation properties

### ISSUE THREAD

**Issue by FlorianFechterTCon** [SAP/cloud-sdk-js#1060]
Hey guys,

we have a question regarding the "Navigation Properties".
Namely, we have a CDS view in the backend with parameters that we want to access. 
The request should look like this:
"/sap/opu/odata/Z_VFW_C_LAYOUT_CDS/VFW_C_LAYOUT(iv_arbpl='RM')/Set?$format=json".
We then tried the whole thing with the Cloud SDK JavaScript documentation by using the following syntax:
"Z_Vfw_C_Layout.requestBuilder().getByKey("RM").select(Vfw_C_Layout.SET)"
Which unfortunately does not give the desired result:
"/sap/opu/odata/CAT/Z_VFW_C_LAYOUT_CDS/VFW_C_LAYOUT(iv_arbpl='RM')?$format=json&$select=Set/*&$expand=Set"

When taking a look at the  Java client documentation, there is a method called "asChildOf" for the ODataV2 Client which seems to do exactly what we need. (https://sap.github.io/cloud-sdk/docs/java/features/odata/use-typed-odata-v2-client-in-sap-cloud-sdk-for-java#navigation-properties)

Is there a similar function on the JS client that we just overlooked?

Best regards,
Florian

**Comment by jjtang1985** [comment]
Hi @FlorianFechterTCon ,

[this](https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v4-type-safe-client-for-javascript-typescript#create-as-child-of) is the `asChildOf` doc of the JS version.

Best regards,
Junjie

**Comment by FlorianFechterTCon** [comment]
hey @jjtang1985,

I had already seen the function but does it also work with "getByKey" or "getAll"?
Since we want to query the data and not update / create some it might be better to compare the functionality we need with "navigateTo" (https://sap.github.io/cloud-sdk/docs/java/features/odata/use-typed-odata-v4-client-in-sap-cloud-sdk-for-java#navigation-properties)

I am sorry if my question was a "little" unclear. ^^

Best regards,
Florian

**Comment by jjtang1985** [comment]
Hi @FlorianFechterTCon ,

since the url is not that readable so I want to make it clear.
Please correct me. I assume 
- `VFW_C_LAYOUT` is an entity set name
- `iv_arbpl` is the key property of the `VFW_C_LAYOUT`
- `RM` is the value of the key `iv_arbpl` that you want to filter
- `Set` is the navigation property name.

Best regards,
Junjie

**Comment by nexzgg** [comment]
Hi @jjtang1985,

its a generated SADL OData v2 Service.
Normaly this service should be called this way.
**/sap/opu/odata/CAT/VFW_C_VUE_LAYOUT_CDS/xCATxVFW_C_VUE_LAYOUT(iv_arbpl='PM1')/Set**
But thats not possible in sap-cloud-sdk odatav2 for now.

[metadata.zip](https://github.com/SAP/cloud-sdk-js/files/6068330/metadata.zip)

**Comment by jjtang1985** [comment]
Hi @nexzgg , @FlorianFechterTCon ,

currently, for the query of the navigation property, the example below is not possible
`https://services.odata.org/OData/OData.svc/Categories(1)/Products`

I'll create a backlog item for this feature request.
May I ask more details of your product? Are you working on a live system or may be a PoC?
@artemkovalyov 

For the time being. I recommend that you try the request with `select` as mentioned in the ticket description. 
```
Z_Vfw_C_Layout.requestBuilder().getByKey("RM").select(Vfw_C_Layout.SET)
```
Is it working?

Best regards,
Junjie

**Comment by nexzgg** [comment]
Hey @jjtang1985,

unfortunately, this approach does not work. Since the call is processed completely differently in the SAP backend.
However, if necessary, we can also provide the service via the transaction SEGW instead of the SADL interface, then this should work.

We are currently building a new product with Vue.js in the frontend and SAP onPremise in the backend. However, the product will certainly still be in the development phase for the whole year.

Best Regards,
Julian

**Comment by nexzgg** [comment]
Hey @jjtang1985,
here is the info you wanted.
![image](https://user-images.githubusercontent.com/53438585/111271878-1b556480-8632-11eb-8973-cf3bcb03d684.png)
![image](https://user-images.githubusercontent.com/53438585/111271898-23150900-8632-11eb-9028-72dc0ceb1706.png)
![image](https://user-images.githubusercontent.com/53438585/111271930-2d370780-8632-11eb-8093-114300abcec6.png)

If i use this Request _/sap/opu/odata/CAT/VFW_C_VUE_LAYOUT_CDS/xCATxVFW_C_VUE_LAYOUT(iv_arbpl='PM1')/Set_
I do not even run into this code.
If I can find some time, I can see where the code diverges.

Best Regards,
Julian.

**Comment by FrankEssenberger** [comment]
Hello everybody,

@jjtang1985 asked me if I would have an idea in this issue. So to summarize the situation:
- We have an issue in the SDK that you can not make request like `Entity(key)/RelatedEntity` we have a backlog item and will address the problem
- If you try the work around with the select/expand you run into an exception. If the service would implement all methods the select/expand approach should work. As @nexzgg pointed out the executed code diverges and it seems like different interface methods are invoked. 

Now guessing from my side starts. I guess you need to model/implement the association when you generate a service via the CDS->SADL->OData flow? I found [this blog post](https://blogs.sap.com/2019/11/27/sadl-handling-odata-navigation-without-association/) here in which some steps are mentioned. 

Since you do not want to adjust this auto generated code I think it is best to wait until we implemented the feature.

Best
Frank

**Comment by nexzgg** [comment]
@FrankEssenberger @jjtang1985 

Hey Guys, 
we solved the problem by just using a function import in a self made service.

Best Regards
Julian

**Comment by jjtang1985** [comment]
Hi @nexzgg,
thank you very much for your updates.

I'll close the ticket and the feature request will remain in our backlog.
We might prioritise once this is requested.

**Comment by jjtang1985** [comment]
Hi @buettnerjulian ,
we implemented a new function `appendPath` so that you can add the missing URL by your own.
In your case, the request should look like below:
```ts
Z_Vfw_C_Layout.requestBuilder()
   .getByKey("RM")
   .appendPath(
     '/Set'
   )
   .executeRaw(destination);
 ```
However, as the request builder cannot deserialise the response data, you have to use `executeRaw` instead of `execute`.
[Here](https://sap.github.io/cloud-sdk/docs/js/features/odata/execute-odata-request#getting-the-raw-response-and-the-original-request) is the doc for `executeRaw`.

You can try it with the `canary` version and we will make a new release soon.

If you have any questions, please reopen the issue.

**Comment by buettnerjulian** [comment]
Hey @jjtang1985,

cool. Thanks a lot. We will try it out soon.

Regards,
Julian
