### ISSUE TITLE
Principal Propagation does not work in node.js v.10 (default in BTP CF).

### ISSUE THREAD

**Issue by carlonnheim** [SAP/cloud-sdk-js#1288]
See the issue posted here:
https://answers.sap.com/questions/13382012/principal-propagation-works-in-bas-but-not-when-de.html

**Comment by jjtang1985** [comment]
Hi @carlonnheim ,

thank you for reaching us.

I checked the link provided. Here are some comments from my side:
- The log says, `No user token (JWT) has been provided! This is strictly necessary for principal propagation.`, which seems to be a CAP issue or CF configuration issue, because without JWT, there is nothing the SAP Cloud SDK can do.
- Adding the node version to the package.json as a fix seems also like a CAP issue, because the  SDK does not need this.
- CAP does not support node 10, and you have to use node 14 and newer version, which seems to be related to your fix.
- Actually the end of life of node 10 is 30-04-2021, I guess CF should not use v.10 as default version.

May I ask you to create an issue [here](https://github.wdf.sap.corp/cap/issues/issues/new/choose) as the support channel of CAP?

Best reagards,
Junjie

**Comment by gregorwolf** [comment]
Hi @jjtang1985 ,

I would suggest to not use links to internal SAP websites.

Best regards
Gregor

**Comment by jjtang1985** [comment]
Hi @gregorwolf,
good catch, I updated the link.
Best regards,
Junjie

**Comment by carlonnheim** [comment]
Hi,

Ok, makes sense. Then this is more of a caveat than a bug (CAP requiring node 14 but the BTP running node 10 by default). Let us close this. Anyone struggling with the same issue will hopefully find the forum post.

Thanks for your feedback and your work on this product, it is an awesome framework!
//Carl
