### ISSUE TITLE
Upload Attachment with API_CV_ATTACHMENT_SRV uploads file with JSON object inside

### ISSUE THREAD

**Issue by ctapisab** [SAP/cloud-sdk-js#1324]
**Describe the bug**
The uploaded content is not saved/sent correctly. It stores a JSON and not the content file.

The documentation I followed is [this](https://api.sap.com/api/API_CV_ATTACHMENT_SRV/resource?tag=Document%20Management&path=post_AttachmentContentSet&method=post&opId=post_AttachmentContentSet) and [this](https://help.sap.com/viewer/7489fa08cede494cbdf08fa3651598af/2105.500/en-US/63259b6826174573bc32f2e1d1609cd9.html).

**To Reproduce**

1. Set up ...
- Add the following code to a SDK Cloud (JS) project.
2. Execute ...
- Execute with `npm run start:dev`
- Make a request to the corresponding endpoint (the following code just has the data hardcoded for demo purposes).
- The code uploads an attachment to S/4HANA linked to the corresponding business object/document.
3. Confirm ...
- Download the uploaded attachment via other API method or from an standard FIORI application.

- The content of the file is (opened with VS Code or a Notepad):
`
{"Content":"...content file here...","MimeType":"application/pdf"}
`

**Expected behavior**
The file should just contain the file data (the value of "Content" in the JSON) and not the JSON object.

**Screenshots**

**Used Versions:**

- node version via `node -v`: 12.18.4
- npm version via `npm -v`: 7.13.0
- SAP Cloud SDK version you used as dependency: 1.32.1

**Code Examples**
```
import { AttachmentContentSet } from '@sap/cloud-sdk-vdm-attachment-service';

const file_buffer = fs.readFileSync(filepath, { encoding: 'binary' });

AttachmentContentSet.requestBuilder()
    .create(
      AttachmentContentSet.builder()
        .content(file_buffer)
        .mimeType('application/pdf')
        .build(),
    )
    .addCustomQueryParameters({
      'sap-client': '100',
    })
    .addCustomHeaders({
      Slug: fileName,
      // 'Content-Type': 'application/json', // Tried with 'application/pdf' as MimeType with the same reuslt
      BusinessObjectTypeName: 'EKKO_QTN', // This example is a Supplier Quotation
      LinkedSAPObjectKey: '8000000003',
    })
    .executeRaw({
      destinationName: 'S4_SYSTEM',
    })    
    .then((data) => {
      console.log(data); // to log request info
    });
```

Tried many ways to get the file (`file_buffer` variable), but all with the same result (stores a JSON).

**Log file**
- Not applicable

**Additional context**
- Not applicable

**Comment by jjtang1985** [comment]
Hi @ctapisab ,

thanks for approaching us.

In order to upload attachments with the service `API_CV_ATTACHMENT_SRV`, I see some points:
- [1] The request body of the POST request has to be a binary data.
- [2] The `Content-Type` header needs to be customised to e.g., `application/pdf`
- [3] When setting the header parameters `Slug`, `BusinessObjectTypeName` and `LinkedSAPObjectKey`, you need to wrap real values with single quotes like, `.addCustomHeaders( { 'Slug' : "'filename.pdf'" } )`.

Therefore, it might be hard to use the current attachment client to reach the goal, because:
- [1] binary data is not supported for the time being
- [2] custom `Content-Type` is not recommended, as in general, the clients only accept json body.

I would suggest to use our [generic http client](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/generic-http-client) so you can build a binary request body [1] and set proper `Content-Type` [2] by your own.
Please note, for [3], make sure you use the single quotes as mentioned.

If you have further questions, please let me know.

Best regards,
Junjie

**Comment by jjtang1985** [comment]
I'll close this ticket, as the generic http client is the recommended way to handle this.
