### ISSUE TITLE
Could not find a destination with name X

### ISSUE THREAD

**Issue by Thymios** [SAP/cloud-sdk-js#1337]
I have implemented an endpoint calling an SAP ECC OData service, configured a destination and bound a destination service instance to my app as described in https://developers.sap.com/group.s4sdk-js-cloud-foundry.html.
I am getting an error saying the destination could not be found, although looking at the app logs it seems that the destination was retrieved successfully.

```
import { Controller, Get, HttpException } from '@nestjs/common';
import { Employee } from '../db/odata-client/hcm-team-calendar-service';

@Controller('employees')
export class EmployeesController {
    @Get()
    findAll() {
        return getAllEmployees()
            .catch(error => {
            throw new HttpException(`Failed to get employees - ${error.message}`, 500);
        }); 
    }
}

function getAllEmployees(): Promise<Employee[]> {
    return Employee.requestBuilder()
        .getAll()
        // .addCustomQueryParameters({ format: 'json' })
        .execute({ destinationName: 'IIE' })
}
```

Log:
[team_calendar-2021-06-04 09.txt](https://github.com/SAP/cloud-sdk-js/files/6597779/team_calendar-2021-06-04.09.txt)

Thanks in advance.

**Comment by FrankEssenberger** [comment]
Godd morning @Thymios,

sorry for the late reply. When I look at the logs they seem fine as you say. After trying the process.env and instance variables it receives the destination from the service:

```
2021-06-04T09:08:06.841+0000 [APP/PROC/WEB/0] OUT {"message":"Successfully retrieved destination from destination service.","level":"info","custom_fields":{"package":"core","messageContext":"destination-accessor-service"},"logger":"sap-cloud-sdk-logger","timestamp":"2021-06-04T09:08:06.841Z","msg":"Successfully retrieved destination from destination service.","written_ts":1622797686841,"written_at":"2021-06-04T09:08:06.841Z"}
```

Where does the error that the destination can not be found shows up, because I do not see it in the logs?

Best
Frank

**Comment by Thymios** [comment]
Hi Frank,

Thanks a lot for reaching out I am super new to BTP, sorry.
The error shows on BTP after deploying the app and visiting the endpoint.
![image](https://user-images.githubusercontent.com/7215002/121519889-ea9b8600-c9fa-11eb-98bb-93b01f6e4466.png)

Tried calling getDestinationFromService  - getDestinationFromDestinationService('my-destination',{}); - in dev mode but it gets rejected: Unable to get access token for "destination" service! No service instance of type "destination" found.

No idea how to log things when running in prod mode.

Thanks in advance,
T

**Comment by FrankEssenberger** [comment]
Thanks for sharing.

`Unable to get access token for "destination" service! No service instance of type "destination" found.` means that there is no destination service around. Since I am not sure what dev and prof mode means, I think it makes sense to go one step back and make a test if you can receive a destination with your CF setup. Without any app running.

For this do the following.
- Go to the Application in CF and investigate the Environment variables view
- Copy  the JSON Object under the key VCAP_SERVICES. (This contains all information to consume services like destination service)
- Create a local script where you execute the `getDestinationFromService('IIE)` method
- Set `process.env['VCAP_SERVICES'] = JSON.stringify(<the object you copied from CF>) before you make the call
- Execute the script

With this you can locally do the same thing as if you were on cloud foundry. Let me know what is returned from the getDestinationFromService call.

Best
Frank

**Comment by FrankEssenberger** [comment]
you have to remove the `VCAP_SERVCIE` in the jsn and put the object - otherwise you have the key twice:
```
jsn = { "xsuaa":[].....}
```
Also I would create just a simple TS file containing:
- set process env
- call the getDestinationFromDestinationService
- Catch error and log them.

Then you execute the file like `ts-node myFile` or you put it even in a .spec.ts file than you can run it in your debugger in VSC.

Best
Frank

**Comment by Thymios** [comment]
Hi Frank,
Tried with a single TS file and got this error:
Error: No binding to a connectivity service found! Please make sure to bind an instance of the connectivity service to your app if you want to connect to on-premise destinations.

These are my service bindings on btp
![image](https://user-images.githubusercontent.com/7215002/121657133-d0b87c80-caa8-11eb-9e5b-c7f23059df1c.png)

Thanks,
Thymios

**Comment by FrankEssenberger** [comment]
Are you trying to connect to an OnPrem S/4HANA system i.e. destination type onPremise? In this case you would need a connectivity service. Perhaps you first create a simple destination with `type HTTP` to some dummy system without any authentication and see if you can fetch this destination. If this is the case your destination service setup is fine. 

For onPrem systems everything is [more complicated](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/on-premise). In general you would need:
- The binding to the connectvity service
- A cloud connector attached to your BTP account

Best
Frank

**Comment by Thymios** [comment]
Binding a connectivity service instance solved it.
Thanks for your time :)

**Comment by FrankEssenberger** [comment]
Cool. I close the issue and add this to our back lock item to improve the logging.
