### ISSUE TITLE
Why is `getDestination` not tenant-aware by default in our scenario?

### ISSUE THREAD

**Issue by LaxOn** [SAP/cloud-sdk-js#1381]
I am from the C4Ufoundation team. We have a multitenant Node.js CAP application [edom-retailer-core](https://github.wdf.sap.corp/c4u/edom-retailer-core). We are using the `cloudSdk.getDestination` function and would like to clarify that the following makes sense:
- We understand that `cloudSdk.getDestination` should be tenant aware by default, but this does not seem to be the case when we use it like below. It gets the destination from the provider subaccount instead of the consumer subaccount
`const dest = await cloudSDK.getDestination('mdi-dest', { useCache: true })`
- In [this issue](https://github.com/SAP/cloud-sdk-js/issues/1262), we were told to include `isolationStrategy`, but this does not work either.
`const dest = await cloudSDK.getDestination('mdi-dest', { useCache: true, isolationStrategy: 'Tenant' })`
- Finally, we pass a `userJwt` and this works
`const dest = await cloudSDK.getDestination('mdi-dest', { useCache: true, userJwt: req.headers.authorization })`

Questions
1. Why is  `cloudSdk.getDestination` not tenant-aware by default in our scenario?
2. Is passing `userJwt` good practice? Is there a more correct way of achieving this?

**Comment by jjtang1985** [comment]
Hi @LaxOn ,

I guess this [documentation](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination) can answer you question 1, where it says
`If no token is given or the destination is not found in the subscriber account the provider account is used as a fallback.`
Please check the link for details.

For question 2, the same documentation says
`The jwt argument takes the JSON web token (JWT) issued by an XSUAA as input. This token contains a field zid holding the tenant id which will be used in the lookup process.`
Therefore, the SDK decode the JWT and use the `zid` for the destination lookup.
If I understand correctly, your question is about API design.
If so, could you please share more details about why do you think passing `userJWT` is not a good practice and what do you mean  with "a more correct way"?

Best regards,
Junjie

**Comment by LaxOn** [comment]
Hi @jjtang1985,

Thank you for responding. Just to follow up:
1. Why would `await cloudSDK.getDestination('mdi-dest', { useCache: true })` fallback to the provider subaccount when our requests require a token taken from the subscriber auth url and should have the subscriber context. Are we missing something? Our subscriber subaccount also has the destination points (eg. mdi-dest) configured
2. My 2nd question ties in with the first one. I wanted to clarify if we really need to pass a `userJWT ` when we are supposed to  already have a subscriber context?

**Comment by LaxOn** [comment]
Hi @jjtang1985,

Just wanted to follow up if you have any updates on our questions above?

Thanks,
Bryan

**Comment by jjtang1985** [comment]
Hi @LaxOn ,

sorry for the late response. I just come back from vacation.

For question 1:
When calling the function `getDestination`, the destination lookup might return a matched destination from provider account or subscriber account based on the [`selectionStrategy`](https://sap.github.io/cloud-sdk/api/1.41.0/modules/sap_cloud_sdk_core#destinationselectionstrategies). You can find more details in this [doc](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination/#multi-tenancy). With proper strategy, one can always find the proper destinations for different use cases.

In your case, if you don't want to get the destination from provider account, you can use `alwaysSubscriber`.
However, even you use this strategy, if you don't provide the JWT, you still cannot get the destination from your subscriber account. You should get nothing instead of the destination from the provider account, as you explicitly mentioned `alwaysSubscriber`.
Now, let's discuss about question 2, as you have to provide the JWT to get the destination from your subscriber account and you ask whether you really need to do so.

For question 2:
Independent to cache, when you call the destination service on behalf of a specific tenant, the JWT has to be used as the authorization header.
You can find more about consuming the destination service [here](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/7e306250e08340f89d6c103e28840f30.html#).

I hope this answers your questions.

Please let me know, if you still have questions.

Best regards,
Junjie

**Comment by jjtang1985** [comment]
Hi @LaxOn ,

would it be fine to close this issue?

Best regards,
Junjie

**Comment by jjtang1985** [comment]
I'll close this issue and please feel free to re-open when necessary.
