### ISSUE TITLE
Parser for SAPUI5 Operators

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-sdk-js#1641]
**Is your feature request related to a problem? Please describe.**
SAPUI5 defines a syntax for [Filters](https://experience.sap.com/fiori-design-web/value-help-dialog/#using-the-filters) which is translated into the needed OData requests by the UI5 Framework. I want to be able to store this filter syntax in my Node.JS based application and get a SAP Cloud SDK functionality that does the parsing for me.

**Describe the solution you'd like**

In the application I would store this filters for the attribute Product:

=4733,=4734 

this should be translated into the OData filter

$filter=Product eq '4733' or Product eq '4734'

Another Example is:

4733*

that should be translated to:

$filter=startswith(Product, '4733') eq true

at the end all Operators can hopefully be translated into their corresponding OData filter parameter. The sourcecode of [sap/ui/comp/providers/TokenParser-dbg.js](https://sapui5.hana.ondemand.com/1.94.1/resources/sap/ui/comp/providers/TokenParser-dbg.js) might be helpful for this feature.

**Describe alternatives you've considered**

I've posted a question in the SAP Community: [Translation of SAPUI5 Operators in CAP / SAP Cloud SDK Backend to OData filters](https://answers.sap.com/questions/13495727/translation-of-sapui5-operators-in-cap-sap-cloud-s.html). Currently we have implemented support for the Equal and Not Equal operator.

**Impact / Priority**

We are about to Release a product. Currently the search options are limited to the Equal and Not Equal operator. As we also  [can't reduce the list of availiable Filter operators for the value help dialog](https://answers.sap.com/questions/13473315/how-to-changereduce-the-filter-operator-list-for-v.html?childToView=13494742) the customer is complaining about the usability.

Affected development phase: Release

Impact: Impaired

Timeline: Go-Live is in 3 month.

**Comment by jjtang1985** [comment]
Hi @gregorwolf ,
Thanks for raising up.

Please correct me.
It seems you only need an "adapter", that accept filters with UI5 syntax and produce filters with SDK syntax.
Then, the output of the "adapter" can be used with SDK core for building the whole OData request.

This feature request seems to be only for `filter`, while the title says "Parser for SAPUI5 Operators
". For a big picture, do we have some other relevant operations in addition to filters?

FYI @artemkovalyov. The timeline is this year.

**Comment by gregorwolf** [comment]
Hi @jjtang1985,

for our usecase the described `adapter` that translates the UI5 syntax for filters into the SDK syntax would be sufficient. Please feel free to adjust the title of this feature request acordingly.

I've taken the term "Operators" from the SAP Fiori Design Guidelines page: [Using the Filters](https://experience.sap.com/fiori-design-web/value-help-dialog/#using-the-filters).

Best Regards
Gregor

**Comment by marikaner** [comment]
Hey @gregorwolf,

we discussed, that this feature could be useful, maybe even for other users, but it seems like an edge case and as of today it does not fit the core functionality of the SAP Cloud SDK.
Your case is special in a sense that you are reusing the SAPUI5 given filter types for your backend, for which it wasn't originally intended to my understanding.

If there was high demand for this feature, we could talk about implementing this - probably in a separate module. But we most definitely could not do it within your requested timeline - even with high demand.

I have two suggestions for you:
1. Maybe you can leverage the UI5 Token parser if you adjust how you store your filters? One naive idea would be to store the resulting query string, instead of the filter.
2. You could implement the token parser as a standalone library. If you make it available for public use, we would be happy to feature this in our documentation.

Let me know what you think about this.

**Comment by marikaner** [comment]
I will go ahead and close this issue. If you think it would be interesting for a broader audience, feel free to comment.
