### ISSUE TITLE
Unable to retrieve SAP S4/HANA On-Premise destination with Kubernetes

### ISSUE THREAD

**Issue by marikaner** [SAP/cloud-sdk-js#1653]
The user has a CAP application with Kubernetes. After updating to the latest version of the SAP Cloud SDK they got the following error:  `Error during request to remote service: Failed to load destination. Caused by: Failed to add proxy authorization header - client credentials grant failed! Caused by: Could not fetch client credentials token for service of type \"connectivity\"/ Caused by: Invalid service credentials: Missing url.`

**Comment by tomfrenken** [comment]
if it worked before, this issue was most likely caused when the connectivity service was recreated in your k8s cluster, currently the connectivity service with the connectivity_proxy plan misses a few fields that it has in its CloudFoundry equivalent.

The current workaround is to edit the connectivity service binding that should be represented as a secret in your cluster and add the field manually, however just like this issue, this workaround will stop working every time the service and its service binding are recreated.

To fix it for now, check if the secret containing the connectivity service binding contains these 3 fields, and if not, add them to the secret:

onpremise_proxy_host: connectivity-proxy.<namespace>
onpremise_proxy_port: <port>, default is 20003
url: should have the same value as token_service_url

To edit the secret just use kubectl edit secret <secret-name>, be aware that you have to add the values encoded in base64, for that you can simply use echo "<value>" | base64, or if you get the value of token_service_url already in its base64 encoded form, just copy it over.

**Comment by i353590** [comment]
Hello @tomfrenken 
I have a similar issue in my app deployed to Kyma. However, my error is a bit different.
Please have a look at the error once and suggest me what could be wrong:

`,"statusCode":502,"reason":{"message":"Error during request to remote service: \nFailed to load destination. Caused by: Failed to add proxy authorization header - client credentials grant failed! Caused by: Could not fetch client credentials token for service of type \"connectivity\". Caused by: Breaker is open","request":{"method":"GET","url":"/A_BusinessPartner?`

Thanks,
Shubham
