### ISSUE TITLE
getDestination with `useCache: true` returns valid grant token when it should not

### ISSUE THREAD

**Issue by johenning** [SAP/cloud-sdk-js#1765]
**Describe the bug**
I'm using `getDestination` with `useCache: true` and am able to get a grant token from the cache, even though I have an invalid token for principal propagation.

I believe this is due to the caching being done on the wrong key: https://github.com/SAP/cloud-sdk-js/blob/b31e3e68065049875b44e077fcb5156a10028fa0/packages/connectivity/src/scp-cf/token-accessor.ts#L49
The `serviceCredentials.clientid` here is static in my case (destination service credentials are statically stored in the `VCAP_SERVICES`) and thus is the same on each request.
For destination access with principal propagation the token.email (or similar) should be considered.

**To Reproduce**

1. Setup application with `VCAP_SERVICES.destination...credentials` set
2. Get a token not suited for principal proagation (e.g. client credentials instead of authorization code) -> `getDestination(..., {useCache: true})` returns 401
3. Get a valid authorization code token -> `getDestination` is successfull
4. Repeat step 2

**Expected behavior**
A 401 is returned again

**Actual behavior**
A valid grant token is returned from cache

**Used Versions:**

- node version: v14.16.1
- npm version: 6.14.12
- SAP Cloud SDK version: 1.51.0

**Code Examples**
```
 service.destination = await getDestination(service.destinationName, {
        userJwt: getJwt(req),
        useCache: true,
      });
```

**Impact / Priority**
High - Unauthorized access might be possible

**Additional context**
If necessary I can provide more details and instruction for how to reproduce this behavior.

**Comment by marikaner** [comment]
Hey @johenning,

thank you for reporting this. We're on it.

**Comment by FrankEssenberger** [comment]
Hi @johenning,

also thanks from my side for bringing this up. The chaching is not correct. I had a look at the code also to see how catastrophic the vulnerability is (deprecating versions etc.).

The way I see it:
- Destination from service method is called storing the [user JWT](https://github.com/SAP/cloud-sdk-js/blob/f43da96fb9efbc5297f4279fa80060d542830c97/packages/connectivity/src/scp-cf/destination/destination-from-service.ts#L103)
- The destination is [received from the service](https://github.com/SAP/cloud-sdk-js/blob/f43da96fb9efbc5297f4279fa80060d542830c97/packages/connectivity/src/scp-cf/destination/destination-from-service.ts#L111) with the caching issue of the service token you found. 
- Form there the JWT is put in the `SAP-Connectivity-Header` of the [proxy config](https://github.com/SAP/cloud-sdk-js/blob/f43da96fb9efbc5297f4279fa80060d542830c97/packages/connectivity/src/scp-cf/destination/destination-from-service.ts#L443)
- This header is send to the S/4 system and will be rejected because it it not valid.

 @johenning  could you perhaps check what happens when you send the request to the S/4 system using the destination you got. I hope you receive a unauthorized because you provided a token not valid. 

I checked for the user JWT related flows:
- [OAuth2SAMLBearerAssertion](https://github.com/SAP/cloud-sdk-js/blob/f43da96fb9efbc5297f4279fa80060d542830c97/packages/connectivity/src/scp-cf/destination/destination-from-service.ts#L122) seems to request a fresh token.
- [OAuth2JWTBearer](https://github.com/SAP/cloud-sdk-js/blob/f43da96fb9efbc5297f4279fa80060d542830c97/packages/connectivity/src/scp-cf/destination/destination-from-service.ts#L143) also most likely ok because the da.fetchDestinationByUserJwt(); as well

For the non user dependent flows like `OAuth2ClientCredentials` you could receive a working destination with a [valid initial JWT](https://github.com/SAP/cloud-sdk-js/blob/f43da96fb9efbc5297f4279fa80060d542830c97/packages/connectivity/src/scp-cf/destination/destination-from-service.ts#L164) using a wrongly cached service token. Even if the JWT is not legit for receiving destinations for the service. This is already bad enough, but I hope these flows are mainly for application to application communication where it is not so easy to fiddle around with the JWT.

Best
Frank

**Comment by FrankEssenberger** [comment]
I thought about the issue over the dinner and I think there is not  a problem. The `serviceToken` gives you a clientCrendentialsGrant for the service. Under which condition you are allowed to receive this token from the xsuaa :
- If you have the service `crendentials`
- The tenant is set via the `xsuaa URL`, which is determined by a validated JWT

The cache considers these two properties which are obtained by the VCAP runtime varialbes and the JWT so there is not way to change this at runtime.

I think one confusing thing is, that the destination service always returns a destination, even if the user specific auth flow fails. In such a case the `authTokens` array in the destination does not contain a token but an error object, telling you something went wrong. 

As a consequence our `getDestionation()` also returns a destination object, if for example you use a JWT with a wrong grant. Perhaps we can change this in the future, that the method already throws an error.

Best
Frank

**Comment by johenning** [comment]
@FrankEssenberger I also looked further into this.

> I thought about the issue over the dinner and I think there is not a problem.

So I might be wrong about the root cause, but there is definitely a problem. Maybe the client-credentials grant example is valid, I am not familiar enough with the topic to judge.

But I have a another reproducible example where I am sure its not the correct behavior:
1. `getDestination` with a valid user for the BST -> 200 ✔
2. `getDestination` with an invalid user for the BST (user does not exist in system) -> 200 ❗ should be 502 with nested 403

Also, it looks like the first request wins (indicating a caching problem). So the other way around:
1. `getDestination` with an invalid user for the BST (user does not exist in system) -> 502 with nested 403 ✔
2. `getDestination` with a valid user for the BST ->  502 with nested 403 ❗ should be 200

I should also mention that this only happens with `useCache: true`. Without it, it works as expected.

> I had a look at the code also to see how catastrophic the vulnerability is (deprecating versions etc.).

Given that an **any** user with a valid JWT for the subaccount can access a destination if it has been accessed by an authorized user before, I would say this qualifies as potentially catastrophic. 
Only good news it that from what I can tell, the token that gets cached is the authToken retrieved from the destination service via the `tokenServiceURL`, which (at least in my example) is only valid for 1 minute

**Comment by FrankEssenberger** [comment]
When I looked in the code I got the impression, that you could get a destination, but the request to the target system should fail. I hope this is true. So in your example what is the authentication type for the target system?

Receiving destinations is something allowed by the account level. So if you have a subscription to the destination service your application can get destinations. It does not matter which user you are. 

But this needs to be investigated and we have the call later on.

**Comment by FrankEssenberger** [comment]
I have been reading over the code a bit more and one thing which could be the reason the the [isolationStrategy](https://github.com/SAP/cloud-sdk-js/blob/f43da96fb9efbc5297f4279fa80060d542830c97/packages/connectivity/src/scp-cf/cache.ts#L41) options. Per default it is set to `tenant`. Could you (perhaps before the meeting) or we do it later together pass a stronger value like [ IsolationStrategy.Tenant_User](https://github.com/SAP/cloud-sdk-js/blob/f43da96fb9efbc5297f4279fa80060d542830c97/packages/connectivity/src/scp-cf/cache.ts#L24) and see if the error persists?

If this is the reason we should change the default to the higher value and start a discussion what should happen to the previous versions. If you have switched on the cache it is a severe problem since you can get destinations not isolated by user - you would receive a destination with a token with not the right user. To exploit this you would need a valid JWT to be let in the application. But if you do this often enough perhaps you get the token from a user with many permissions.

**Comment by johenning** [comment]
> Could you (perhaps before the meeting) or we do it later together pass a stronger value like IsolationStrategy.Tenant_User and see if the error persists?

Tried it like this:
```javascript
      service.destination = await getDestination(service.destinationName, {
        userJwt: getJwt(req),
        useCache: true,
        isolationStrategy: IsolationStrategy.Tenant_User,
      });
```
Error persists (also with just `User`).

> So in your example what is the authentication type for the target system?

`OAuth2SAMLBearerAssertion`

> Just to be clear the http codes come from the target system or the getDestination() request?

I think we might be setting the 502 when `getDestination` fails, the CloudSDK error is `Failed to build headers` with the 403 inside of the `rootCause` which is coming from the destination service. The 200 is the result from the target system

**Comment by FrankEssenberger** [comment]
hm, this is puzzling. I am looking forward to the session later.

**Comment by FrankEssenberger** [comment]
Does your JWT have a filed `user_id` because we read and use this to build the cache key.

**Comment by FrankEssenberger** [comment]
We were able to find the cause in the call, that the wrong token is passed in the cache. I also understood why the `alwaysSubscriber` did lead to an error. These two PRs should fix it:

- https://github.com/SAP/cloud-sdk-js/pull/1769 -> reason wrong token is passed
- https://github.com/SAP/cloud-sdk-js/pull/1770 -> broken cache keys are not passed

@johenning thanks once more for bringing this up. I hope we do not have things like this so often, but the next time feel free to contact us via an internal channel, then we would do the whole fix and discussion on a private channel and release it once the fix is available.

**Comment by FrankEssenberger** [comment]
Version 1.52.0 is released and already available on [npm](https://www.npmjs.com/package/@sap-cloud-sdk/core). Please migrate to this version to fix the issue.
