### ISSUE TITLE
Please provide more documentation on OnPremise type destinations for local development

### ISSUE THREAD

**Issue by piejanssens** [SAP/cloud-sdk-js#1856]
_The proxy is only reachable from the Cloud Foundry space, so you cannot use that flow for applications running outside of Cloud Foundry._ [source](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/on-premise#:~:text=The%20proxy%20is%20only%20reachable%20from%20the%20Cloud%20Foundry%20space%2C%20so%20you%20cannot%20use%20that%20flow%20for%20applications%20running%20outside%20of%20Cloud%20Foundry.)

- Does this mean the application has to be deployed on CF in order to get the connectivity service to accept the proxy requests?
- Are there any known workarounds or proxy to proxy solutions to allow local development with connectivity to the on premise system  (UAA+dest+connectivity in default-env.json)?

**Comment by piejanssens** [comment]
I will give this a go: https://github.com/jowavp/sap-cf-proxy

**Comment by FrankEssenberger** [comment]
I made a PR to extend the documentation with the two choices:
- BAS has some functionality, but this would require to use BAS which is in my opinion not comparable to a local IDE.
- If you have VPN access you could use a local environment destination in you tests and the proper full when you are deployed on CF.

I had a quick look at the repo mentioned above and something like this should work as well. Just be careful that your endpoint for the SSH connection is well protected and you have a secure tunnel. We know @gregorwolf from other issues and to my experience he knows what he is doing but just have a look what the code example does. Not that you make a system reachable by accident.

I was hesitant to put the mentioned idea/repo in our documentation since we have to be on the save side for such security relevant things.

**Comment by piejanssens** [comment]
I just found a much easier way for my local development, which doesn't require a separate deployed app and a local proxy app: 

1. Enable SSH for the CF app (could be a dummy app or the actual app already being deployed in CF)
2. Tunnel the ports 20003/20004 
3. Change `onpremise_proxy_host` to `localhost` in `default-env.json`

**Comment by FrankEssenberger** [comment]
Thanks for investigating this elegant solution. Do you have an official documentation for the `enable SSH for the CF app` at hand? Then I would extend the PR with this last option and I do not have to look it up.

Just to summarise in my own words. You would open a tunnel for A->B:
- A is the locahost end and some dummy prot e.g. 1234
- B is the application in CF and the port is the value onpremise_proxy_host  in your VCAP i.e. 200003

Then in your local VCAP variables you set: `onpremise_proxy_host` to `localhost` and `onpremise_proxy_port` to `1234` so that your traffic goes from your local app via the tunnel to the connectivity proxy (in CF) and from there to the onPrem system. Right? 

Best
Frank

**Comment by piejanssens** [comment]
@FrankEssenberger I updated my instructions above and [here you can find the official CF doc](https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#ssh-common-flags).

**Comment by gregorwolf** [comment]
In combination with the Cloud SDK the `cf ssh` only solution is great. I'm using [sap-cf-proxy](https://github.com/jowavp/sap-cf-proxy) to call the on-premise system using the VS Code extension REST Client. The CF Proxy does all the authentication stuff and I can send just the pure HTTP requests. Running the CF Proxy on the developer machine should have no security issues as long as the port is not exposed.

**Comment by FrankEssenberger** [comment]
I will add the ssh options also to the docs and close this issue if this is ok for you?

**Comment by piejanssens** [comment]
Yes, fine for me. 

Consider detecting local development and pointing to that documentation in case connectivity is used to avoid developers losing time on https://github.com/SAP/cloud-sdk-js/issues/1855 😉

**Comment by FrankEssenberger** [comment]
I create a BLI to add some longs depending on the environment.

**Comment by lucasrigo-numen** [comment]
> I just found a much easier way for my local development, which doesn't require a separate deployed app and a local proxy app:
> 
> 1. Enable SSH for the CF app (could be a dummy app or the actual app already being deployed in CF)
>    `$ cf enable-ssh <app> && cf restart <app>`
> 2. Tunnel the ports 20003 (http) and/or 20004 (socks5)
>    `$ cf ssh <app> -L 20003:connectivityproxy.internal.cf.eu10.hana.ondemand.com:20003`
> 3. Change `onpremise_proxy_host` to `localhost` in `default-env.json`

Thank you. This worked on my CAP application.
The only differences is that on "2" I followed the [documentation ](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/on-premise) and used the onpremise_proxy_host, 10.0.4.5, instead of connectivityproxy.internal.cf.eu10.hana.ondemand.com .
The other difference is that I had to adapt "3" to `.cdsrc.json`, I added the onpremise_proxy_host property to the connectivity config, afted the service is already bound with `cds bind`:
```
"connectivity": {
  "binding": {
  ...
  "credentials": {
    "onpremise_proxy_host": "localhost"
  }
  ...
  }
}
