### ISSUE TITLE
Remote service with oAuth2.0 authentication failing

### ISSUE THREAD

**Issue by aleemuddin** [SAP/cloud-sdk-js#1932]
Hello Team,
I was following the remote service execution guide, to call a Odata service from an CAP app hosted on CF.
I am able to export the edmx and generate the service etc locally.
The service that i want to consume is protected via oAuth2.0 Credentials.

when i deploy the project and try to fetch the data from the service i get the below error

[APP/PROC/WEB/0] ERR [cds.remote] - ErrorWithCause: Failed to build headers.
[APP/PROC/WEB/0] ERR at new ErrorWithCause (/home/vcap/app/node_modules/@sap-cloud-sdk/util/dist/error-with-cause.js:34:16)
[APP/PROC/WEB/0] ERR at /home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/http-client/http-client.js:213:15
[APP/PROC/WEB/0] ERR at processTicksAndRejections (node:internal/process/task_queues:96:5)
[APP/PROC/WEB/0] ERR Caused by:
[APP/PROC/WEB/0] ERR Error: The destination tried to provide authorization tokens but failed in all cases. This is most likely due to misconfiguration.
[APP/PROC/WEB/0] ERR Original error messages:
[APP/PROC/WEB/0] ERR Failed to create SSL connection
[APP/PROC/WEB/0] ERR at headerFromTokens (/home/vcap/app/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/authorization-header.js:142:15)

if i use the same credentials in post man, i am able to hit the service directly and get the data.
Please let me know if any more details are required. I have attached the zip of the project as well

[Uploading refApp.zip…]()

refApp |  
-- | --
Node.js | v14.15.0
@sap/cds | 4.6.6
@sap/cds-runtime | 2.9.12
@sap/cds-compiler | 1.50.10
@sap/cds-dk | 3.3.2

Please let me know if any more info is required.

Thank you & Regards
Syed Aleemuddin Noor

**Comment by FrankEssenberger** [comment]
Hello @aleemuddin,

to give you some context the sdk does the following when resolving the destination from BTP:
- Get all destinations with basic information
- Make a second call for the specific destination triggering the token retrieval (OAuth2ClientCredentials in your case)
- The token retrieval is done by the destination service 
- The destination service puts the token in the `authTokens` properties of the returned destinations

Here something goes wrong and the destination service can not fetch the client credential grant token. The original error from the service is: `Failed to create SSL connection`. Since the the other steps work the basic setup seems fine:
- VCAP service credentials to call the destination service
- You can reach the service and it responds

Before we reach out to the colleagues from the destination service to find out what could cause a `Failed to create SSL connection` in the token retrieval I would like to double check all inputs - you mentioned that you can reach the system via postman. However, could you please try to fetch a clientCredentialGrant token as described [here](https://help.sap.com/viewer/8d8be6a74e4e49589a546c02ee193741/latest/en-US/f1eff1dd7907469491989b3a36e6a7c6.html). 

Best
Frank

**Comment by aleemuddin** [comment]
Hi @FrankEssenberger ,
Just tried to fetch the token as described [here](https://help.sap.com/viewer/8d8be6a74e4e49589a546c02ee193741/latest/en-US/f1eff1dd7907469491989b3a36e6a7c6.html)
i was able to fetch the token 
![image](https://user-images.githubusercontent.com/2527086/148032981-33736163-1754-4bd6-8d4a-a6c096e062f5.png)

Let me know if i need to try anything else.

Thank you & Regards
Syed Aleemuddin Noor

**Comment by FrankEssenberger** [comment]
Thanks, so this all looks fine. I will write to the colleagues from the destination service to see what the SSL error could mean.

**Comment by FrankEssenberger** [comment]
@aleemuddin the `Failed to create SSL connection` is most likely indicating that the tokenServiceUrl is not correct. Since it is working in postman the "common" option is selected which leads to a change in the service url as described [here](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/4e1d742a3d45472d83b411e141729795.html). Please use the option "dedicated" if you are not in a multi tenant scenario or use the `{tenant}` wildcard to get a proper tokenServiceUrl.

Please let us know if this solves the issue.

Best
Frank

**Comment by aleemuddin** [comment]
Hi @FrankEssenberger,
Thanks for the communication with the destination team.
The issue was primarily due to an UI issues where the config of destinations wasn't getting set to "dedicated".
The destinations teams advised the following -> "Click edit -> Select Common -> Select Dedicated -> Save and it should work"
after doing this step, the services started to work and authentication was happening as expected.

Thank you & Regards
Syed Aleemuddin Noor
