### ISSUE TITLE
Support for oAuth2Password authentication to OnPremise systems via Cloud Connector

### ISSUE THREAD

**Issue by carlonnheim** [SAP/cloud-sdk-js#1939]
Hi,

We have a use case involving an on-premise system which does authentication with oAuth2Password flow. This is introduced for external services in issue #1399 but trying this with an on-premise destination results in a "not supported"-error being thrown.

There is a forum post here with more details:
https://answers.sap.com/questions/13556967/oauth2password-authentication-in-connectivity-serv.html

We have established a workaround like this:
- Create two destinations, one with NoAuthentication and one with oAuth2Password authentication
- Get the oAuth2Password destination so that the code can access client secret, client id, username and password
- Call the authentication endpoint using the above credentials over the "NoAuthentication" destination
- Build a "Bearer ..." authentication header and call the API using the "executeHttpRequest" method over the NoAuthentication-destination.

This results in a lot of code in the application which we are hoping could be in the framework instead (handling the token provisioning, renewal tokens etc.).

Thanks in advance and for your work on this product!

Regards
//Carl

**Comment by carlonnheim** [comment]
Ok!

Our timeline is Q2 this year with a productive golive.

Thanks!
//Carl

**Comment by jjtang1985** [comment]
Hi @carlonnheim ,

This [documentation](https://help.sap.com/products/BTP/df50977d8bfa4c9a8a063ddb37113c43/765423ddb66147bc8141607a8522fe65.html?locale=en-US) says, on-prem system with auth type `OAuth2Password` is not supported.

Would you like to switch to e.g., basic auth?

Best regards,
Junjie

**Comment by carlonnheim** [comment]
Hi,

Yes, a feature request and not a bug. The target system only supports oauth so I do not have a choice.

We will keep using the workaround and hoping you will consider it for your backlog.

I would also be happy to contribute a PR implementing it if you can give a high level approach and do security validation on it?

Thanks!
//Carl

**Comment by jjtang1985** [comment]
Hi @carlonnheim,

In general, to make a real request to a target system you need:

1. [SDK] Get a destination (containing all the configuration shown in the previous link) by name provided by you.
2. [SDK] Retrieve a token by sending the destination configuration to the destination service on the BTP.
3. [Destination service] Verify the credentials info and return a valid token or error.
4. [SDK] Use the token from the destination service and add it to the header of the real request.

As the step 3 is handled by the destination service on the BTP. This feature request needs to be done on the BTP side.
Please consider creating an incident for SAP BTP by checking [this](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/5dd739823b824b539eee47b7860a00be.html?locale=en-US).

On the other side, your finding makes sense and this bug is also related to cloud destination.
We will work on it.
If your workaround works, after fixing it, you can also try it with your on-prem destination.

We will let you know, once the bug is fixed.

Best regards,
Junjie

**Comment by jjtang1985** [comment]
Hi @carlonnheim ,

I fixed the missing token from SDK perspective and you can test the `canary` version.
Please let me know whether it works for you.

Best regards,
Junjie

**Comment by marikaner** [comment]
Since this was fixed in [v1.54.0](https://github.com/SAP/cloud-sdk-js/releases/tag/v1.54.0) I'll go ahead and close this issue.
