### ISSUE TITLE
cds.RemoteService the destination-configuration service is requesting every time before running queries.

### ISSUE THREAD

**Issue by Alexshov** [SAP/cloud-sdk-js#1996]
Dear Team,

We have an external service **mdiDestService** defined as follows:
```swift
srv.on('replicateProducts', async (req) => {
    ....
    const mdiDestService = await cds.connect.to('MDIDestination');
    while (moreData) {
       ....
       const response = await mdiDestService.run(RequestUrl);
       ....
    }
}
```

The configuration of the **Destination** service in **package.json**:
```swift

   "cds":
      "requires": {
       ....
               "MDIDestination": {
                    "kind": "rest",
                    "credentials": {
                        "destination": "EXT-MDI",
                        "requestTimeout": 30000
                    },
                    "destinationOptions": {
                        "useCache": true
                    }
                }
      ...
      }
```

Each and every time we **run** the request (mdiDestService.run(e.g. https://one-mds.cfapps. ....), the application log shows additional requests to the **destination-configuration** service.

![image](https://user-images.githubusercontent.com/23244222/150295233-208a17f8-a7cc-4844-b938-768746fa0b1a.png)

We'd like to avoid this behaviour and have only one request against **destination-configuration** service . 

Are there any options to cache the destination definition??

### Details about your project

| Component | Version |
|:------------------|---------------------------------------|
| @sap-cloud-sdk/core     | 1.53.0                               |
| @sap/cds          | 5.7.4                                 |
| @sap/cds-dk       | 4.7.2                                 |

**Comment by FrankEssenberger** [comment]
Just a comment, that the caching also depends on the `isolationStrategy` and used authentication flow. The default `isolationStrategy` is `TenantUser` which means that if the calls are related to different users it is expected that multiple calls are send. 

The isolation strategy `Tenant` only makes sense if the auth flow of the destination is not user dependent for example `Basic` or `ClientCert`.

But I guess you re-executed the call to the service endpoint multiple times with the same user right?

Best
Frank

**Comment by FrankEssenberger** [comment]
one more thing came to my mind. The default strategy is the strongest isolation so `TenantUser` if you call the get destination without a user JWT the user can not be determined and the cache key does not contain a user and the cache is not use to prevent wrong cached destinations to be returned. If you use the cache without passing a JWT set the isolation stratgy to `Tenant`. There should be a log statement warning the the cache is not used due to missing user information in such a case.

**Comment by Alexshov** [comment]
Hi @tomfrenken ,

Yes, you are right, we applied a cache, try to call the query in a loop (with different params) and still have a request against the destination service each ana every time.

The problem is - we don't use the pure SDK libruary, but [CAP RemoteService](https://cap.cloud.sap/docs/node.js/remote-services) libruary which is according to the [CAP Team](https://github.tools.sap/cap/issues/issues/10794) should just call SDK libruary and pass all parameters.

In my case I defined `useCache `option as `destinationOptions `of the **CAP RemoteService**, see a schreenshot.

To @FrankEssenberger I have not defined the `isolationStrategy` explicitly.
`But I guess you re-executed the call to the service endpoint multiple times with the same user right?` Yes, you are right.

![image](https://user-images.githubusercontent.com/23244222/150750806-e6ad7f1a-9223-4490-851d-50ea8e293adf.png)

**Comment by FrankEssenberger** [comment]
Hm, this is strange. The logs state that the destination was taken from the enviorment variables. Which is the first step in the chain of lookup and was introduced for test purposes, which is why we have still this log statement about non productive use. We will adjust this in version 2.0 of the SDK.

If the destination is read from the environment, it should not call the destination service at all: https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination:
1. Check env varialbes if it is there stop
2. Check Destination service instance destination if it is there stop
3. Make a call to the destination service

Since the lookup of an environment variable is as expense as to check a cache (both memory operations), we only included the cache in the lookup from the destination service. So to see the log statement multiple times is expected even with the cache switched on.

However, in your initial screenshot there were multiple calls to the destination service, these should be cached, but should not appear if the destination is not found in the environment variables. Can you check:
- if the calls to the service are still present
- is the same  destination requested for which you see the log statement that you got ti from the enviorment varialbe `...-MDI` as name
- Do you have a user JWT (which I guess should be handled by CAP under the hood so hard to tell) and what is the autehntication flow for the destinations you fetch?

Best
Frank

**Comment by marikaner** [comment]
@Alexshov were you able to resolve this issue in the meantime?

**Comment by Alexshov** [comment]
> @Alexshov were you able to resolve this issue in the meantime?

No, we also experienced memory leaks and performance issues in our solution. So decided to to switch to the axios.

**Comment by marikaner** [comment]
@Alexshov That's a pity. Do you know where these issues originated from? In case you had issues with the SDK, I would be very interested whether you see any potential for improvement. I will close this issue for now.
