### ISSUE TITLE
How to configure log level for different modules?

### ISSUE THREAD

**Issue by johannes-vogel** [SAP/cloud-sdk-js#2236]
Hello colleagues,

as of now, we use two of your modules (`@sap-cloud-sdk/http-client` and `@sap-cloud-sdk/connectivity`).
If we want to set the log level for the modules, we need to require a third package `@sap-cloud-sdk/util`.

Is it possible to set the log level for a package without requiring the `util` package?

**Comment by FrankEssenberger** [comment]
Hello @johannes-vogel,

since the `createLogger` method is also in the `util` package I think that the util package is already a dependency from the mentioned modules. So if you ad the `util` package as explicit dependency should not create extra overhead, if the packages are hoisted correctly by `npm`. In general we use the same version modifier e.g. ^2.0.1 in all places so this should work.

Let me know if this answers your questions or if you have problems with multiple `util` dependencies in your node_modules.

Best
Frank

**Comment by johannes-vogel** [comment]
Hi @FrankEssenberger,

yes, I am aware that this is a dependency of the mentioned modules.

However, I don't like the approach of using a module without adding it to the dependencies.
With that, we'd rely on your package structure and that this doesn't change.
I'm also afraid of your point. If we upgrade the version of the SDK within `@sap/cds` and a stakeholder still uses version 1 of the SDK, we are in trouble.

Best regards,
Johannes

**Comment by danjoa** [comment]
Please don't downrate this. it is really very strange API design. I'd expect an API design like that: 

1. we should only have to use `http-client`. 
2. which should provide a way to set log levels → passing through to your `util` internally
3. which should handle destinations behind the scene

**Comment by FrankEssenberger** [comment]
I think we should not mix the two problems:
- API design 
- Rely on package structure
- NPM dependency management 

Regarding the first point @danjoa , I do not find this a "strange" API design. The logger is a separate entity located in util. It is used by the http client, generators, OData clients.... So it makes sense to have it in a separate module. The actual question is does it make sense to re-export the logger API from the util to the http-client so that you can invoke it from this package? I think this is not a good idea, because we would add a lot of boiler plate code of re-exports to all other modules.

Regarding package structure. Unfortunately the situation in node is not so clear as in Java, where there is a logging interface and the consumer needs to provide an implementation.  If a sdk module creates logs, you can be sure that the sdk logger is used to create the logs. In the end, you must rely on this either way. If we would stop using the sdk logger, the `setLogLevel` would not do anything. If you include it as an explicit dependency your code will still work but silently do nothing. If you do not include it, it will fail because the methods are not there anymore. Both situations are bad, but as I said this should not happen because we will use the sdk logger to create logs. 

Regarding the point of having two incompatible versions (1.X and 2.X) in the same project, I think there is not much you can do. Since the version modifiers are not compatible hoisting will not work and the two versions will stay. Which is fine in principle. However, for a thing like a logger where there is some global mapping logger<->level in memory having to implementation having this mapping will lead to undefined behavior. So this should be avoided but I honestly do not know how you can do this in npm.

Best
Frank

**Comment by jjtang1985** [comment]
Hi @johannes-vogel ,

I would like to point out that the package `@sap-cloud-sdk/http-client` has direct dependencies:
- @sap-cloud-sdk/connectivity
- @sap-cloud-sdk/util

Therefore, adding the other 2 dependencies will not require any disc space for installation, if you have the `@sap-cloud-sdk/http-client` already.

Best,
Junjie

**Comment by FrankEssenberger** [comment]
Since we have not heard back for a while I will close this issue for now.  We also adjusted the [default log level in some places ](https://github.com/SAP/cloud-sdk-js/pull/2486) so this could perhaps mitigated the issue already. If not feel free to reopen.

Best
Frank
