### ISSUE TITLE
Support for Content-ID in a Batch request

### ISSUE THREAD

**Issue by techaware** [SAP/cloud-sdk-js#2255]
**Is your feature request related to a problem? Please describe.**

I have observed that SAP Cloud SDK doesn't support Content-ID parameter in a batch request using OData V4 client. I can use addCustomHeaders method to add Content-ID to a request. However, in a batch call with a changeset Content-ID is expected at a Changeset level and not at request level. [Here's](https://www.odata.org/documentation/odata-version-2-0/batch-processing/) the specification from OData org. Section 2.2.1 talks about Content-ID in a changeset. 

Here's a sample payload received by S/4 when addCustomHeaders is used on the patch request. 
![2022-03-07_10-53-49](https://user-images.githubusercontent.com/13560153/157106998-c25924a2-9c63-48db-b6f0-cdffd42a95a9.png)

This results in an error in S/4 regarding missing Content-ID. 

**Describe the solution you'd like**
I would like to add the feature to add Content-ID parameter in batch-request-serializer.js where header parameters 'Content-Type' and 'Cotent-Transfer-Encoding' is appended to a Changeset. 

Also, update batch-change-set.js to support a new property contentid (just like boundary property). 

Here's the correct batch payload with content-id: 
<img width="1272" alt="2022-03-07_12-12-06" src="https://user-images.githubusercontent.com/13560153/157110665-deaf7361-d856-4b23-bf30-ae7e94a28937.png">

**Describe alternatives you've considered**
A quick workaround I tried was to set contentid header parameter on the request using addCustomHeaders and using it to set contentid at changeset level. This is not a clean solution and will have sideeffects. 

**Impact / Priority**

Affected development phase: e.g.  Development

Impact: Blocked

Timeline: e.g. Go-Live is in 15 weeks.

**Comment by jjtang1985** [comment]
Hi @techaware ,

Thanks for raising this up.

I see the missing changeset header support.
Please correct me, it seems the mentioned use case is completely blocked as no work around is available.
For the time being, you might want to use multiple normal requests instead of batch, which is not a perfect solution, unfortunately:(

@artemkovalyov, @marikaner  FYI.

Best regards,
Junjie

**Comment by techaware** [comment]
Hi @jjtang1985, 

Unfortunately, the alternative of calling S/4 multiple time is not acceptable from performance perspective. We have deep entities and would like to post them together as a changeset. 

Can I create/submit a pull request with the fix I proposed?

Regards,
techaware.

**Comment by marikaner** [comment]
Hey @techaware,

are looking for a possibility to customize content-ids or do you just need the content-ids to be there?

Regards,
Marika

**Comment by marikaner** [comment]
@techaware Can you please explain the use case, where you need to configure the content-ids of the requests?
The reason I am asking is, that currently our API does not include a layer to configure the change-request part layer of the request, only the request itself. The solution you presented in your PR unfortunately would mix concerns and in order to propose another API, I would need to understand why it is not sufficient to have it generated by the SDK.

**Comment by techaware** [comment]
Hi @marikaner  - SDK generated Content-ID would work only in certain scenarios where requests in the ChangeSet are independent of each other. 
For example, this [scenario](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_ReferencingNewEntities) will not work. 

I think an API is required to GET/SET the content-ID for the requests within a ChangeSet to give more control to the client while creating a batch request. 

Also, note that the name of the content ID parameter should be 'Content-ID' and not 'Content-Id'.
