### ISSUE TITLE
Support onlySubscriber in JS library for Destination Client

### ISSUE THREAD

**Issue by ww917352** [SAP/cloud-sdk-js#2366]
**Is your feature request related to a problem? Please describe.**

There has been a new and safer strategy `ONLY_SUBSCRIBER` added to fetch *only* consumer sub account content. With this strategy, fetching destination content would result in an error being thrown if there is no consumer sub account in the context. Cloud SDK Java library already supports it. We are using JS library for our node app. We need this strategy so there will be no risk of accidentally exposing destinations from provider sub account.

**Describe the solution you'd like**

Please add `onlySubscriber` to the supported strategies.

**Describe alternatives you've considered**

We are using `alwaysSubscriber` now, which is not as safe as `onlySubscriber`.

**Impact / Priority**

Affected development phase: Development

Impact: Security risk

Timeline: Go live in 2 months.

**Comment by jjtang1985** [comment]
Hi @ww917352 ,

Thanks for raising up.
I created a ticket in the backlog.
@marikaner , FYI.

**Comment by ww917352** [comment]
Thank you so much @jjtang1985

**Comment by FrankEssenberger** [comment]
Hello @ww917352,

I would like to understand why you consider this a security risk? Do you allow users of the subscribed application to search destination by name where the name is provided by the user? We will implement the case anyhow to allow for all options and also align with the scope of Java, I just want to understand the usecase a bit better.

Best
Frank

**Comment by ww917352** [comment]
Hi Frank @FrankEssenberger ,

Yes, a destination is chosen by users for executing an API, and the destination belongs to the customer sub account. We are concerned, for whatever reason the customer tenant information is not in the context, we end up (however slim the chance would be) exposing a destination of the same name in the provider sub account. The `AlwaysSubscriber` strategy, in my opinion, was incorrectly designed. We had discussion with the architects and developers, and as a result `OnlySubscriber` was introduced (because they could not just change the behaviour of `AlwaysSubscriber`).

Cheers,
Wei

**Comment by FrankEssenberger** [comment]
@ww917352 thanks for explaining that. I think your discussion was with the Java team and the implementation are really different in Java and JS since in JS you pass the JWT along the calls it should already work in JS with the `AlwaysSubscriber` - I think. I had a quick look at the relevant code and the check [isProviderNeeded](https://github.com/SAP/cloud-sdk-js/blob/084dc3ddce67da191ee78224c288f2690d8a5a2b/packages/connectivity/src/scp-cf/destination/destination-from-service.ts#L538) should directly stop if the selection strategy is `alwaysSubscriber` and do not touch the provider account.

Could you try it out? 

Best
Frank

**Comment by marikaner** [comment]
Hey @ww917352, as the feature you requested is most likely already supported as you would like to have it, I will go ahead and close this feature request. Please let us know if this does not work for you.
