### ISSUE TITLE
Failed to verify JWT - reintroduced....

### ISSUE THREAD

**Issue by nocheintobi** [SAP/cloud-sdk-js#2480]
Hey,
When migrating from cloud-sdk 2.1.0 to 2.3.0, the following issue occurs, which is kind of related to #2211:
I'm trying to execute a VDM request via a destination. The destination is determined via `@sap-cloud-sdk/connectivity`s `getDestination` function provided with a JWT issued via `@sap/xssec`s `requests.requestClientCredentialsToken` for the destination service...
As worked out in #2211 and meanwhile documented in the migration guide, I've set `iasToXsuaaTokenExchange` to `false`.
Working with `@sap-cloud-sdk/connectivity@2.1.0` everything's fine, but breaks when using `@sap-cloud-sdk/connectivity@2.2.0` (or above) with the stack trace listed below.
The other cloud sdk libs can be used eiter in 2.1.0/2.2.0/2.3.0, only the connectivity module causes the issue.

Stack trace:
```
[cds] - ErrorWithCause: Failed to verify JWT.
    at /path/to/project/node_modules/@sap-cloud-sdk/connectivity/src/scp-cf/jwt.ts:118:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Function.getSubscriberToken (/path/to/project/node_modules/@sap-cloud-sdk/connectivity/src/scp-cf/destination/destination-from-service.ts:159:20)
    at Function.getDestinationFromDestinationService (/path/to/project/node_modules/@sap-cloud-sdk/connectivity/src/scp-cf/destination/destination-from-service.ts:94:7)
    ... // my user code....
Caused by:
Error: Jwt token with audience: [
  'sb-clonexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!byyyy|my-xsappname!bzzz',
  'uaa'
] is not issued for these clientIds: [ 'sb-myapp!txxxx', 'myapp!txxxx' ].
    at returnError (/path/to/project/node_modules/@sap/xssec/lib/validator.js:254:25)
    at /path/to/project/node_modules/@sap/xssec/lib/validator.js:306:36
    at TokenInfo.<anonymous> (/path/to/project/node_modules/@sap/xssec/lib/tokeninfo.js:140:24)
    at /path/to/project/node_modules/jsonwebtoken/verify.js:223:12
    at /path/to/project/node_modules/@sap/xssec/lib/verificationkey.js:111:24
    at KeyCache.getKey (/path/to/project/node_modules/@sap/xssec/lib/keycache.js:191:16)
    at VerificationKey.loadKeyXSUAA (/path/to/project/node_modules/@sap/xssec/lib/verificationkey.js:104:18)
    at Object.module.exports [as verify] (/path/to/project/node_modules/jsonwebtoken/verify.js:94:10)
    at TokenInfo.verify (/path/to/project/node_modules/@sap/xssec/lib/tokeninfo.js:128:20)
    at /path/to/project/node_modules/@sap/xssec/lib/validator.js:269:30 {
  cause: Error: Jwt token with audience: [
    'sb-clonexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!byyyy|my-xsappname!bzzz',
    'uaa'
  ] is not issued for these clientIds: [ 'sb-myapp!txxxx', 'myapp!txxxx' ].
      at returnError (/path/to/project/node_modules/@sap/xssec/lib/validator.js:254:25)
      at /path/to/project/node_modules/@sap/xssec/lib/validator.js:306:36
      at TokenInfo.<anonymous> (/path/to/project/node_modules/@sap/xssec/lib/tokeninfo.js:140:24)
      at /path/to/project/node_modules/jsonwebtoken/verify.js:223:12
      at /path/to/project/node_modules/@sap/xssec/lib/verificationkey.js:111:24
      at KeyCache.getKey (/path/to/project/node_modules/@sap/xssec/lib/keycache.js:191:16)
      at VerificationKey.loadKeyXSUAA (/path/to/project/node_modules/@sap/xssec/lib/verificationkey.js:104:18)
      at Object.module.exports [as verify] (/path/to/project/node_modules/jsonwebtoken/verify.js:94:10)
      at TokenInfo.verify (/path/to/project/node_modules/@sap/xssec/lib/tokeninfo.js:128:20)
      at /path/to/project/node_modules/@sap/xssec/lib/validator.js:269:30 {
    statuscode: 401
  }
```

Btw, I do not provide a custom issuer via `iss` property...

Do you have any suggestions on what needs to be changed when upgrading?

Thanks in advance,
Tobi

**Comment by FrankEssenberger** [comment]
Hello Tobi,

we reproduced the timeline of events:
- 16.2 Bump version of XSSEC to version 3.2.13
- 17.1 Release SDK version 2.1.0 (still working)
- 28.2 Use xssec also for validation of token
- 6.4 Release SDK version 2.2.0 -> error appears

So the error is related to XSSEC checking more than we did before. Our old custom implementation only got the certificate and checked that the signature matched. No check on audience. The library now checks that the audience meet some conditions which is not the case. 

I have access to the internal code base and see many tests and there are many conditions on the audience, scopes and clientIds. I am no expert there but I would assume they know what they are doing :-). I would recommend to things:

- Try to create a JWT for the XSUAA service. This is just an idea but it feels more correct since the XSUAA is the entry point and tokens will be cast to the service token later down the flow anyway. We have a convinience method for that:
[serviceToken('xsuaa')](https://github.com/SAP/cloud-sdk-js/blob/b7620cbedda4399f4ae8d83f498602f17b0f0174/packages/connectivity/src/scp-cf/token-accessor.ts#L26)
- If you do not provide a JWT at all, the SDK will request a JWT for the destination service. It will use the clientId and secret from vcap and as a tenant the provider account where the application is currently running. This token is not validated because we got it from the XSUAA and it is valid. So perhaps this could be a solution, or could you perhaps explain why you need to create a JWT manually?


Best
Frank

**Comment by nocheintobi** [comment]
Hi Frank,
since I'm dealing with a multitenant environment, the second option is not an option for me.
Before upgrading, I fetched the destination token for the current tenant via 
`requests.requestClientCredentialsToken(tenant, getDestinationServiceCredentials(), null, (err, token) => resolve(token))` where `requests` is part of `@sap/xssec`. 
In order to get a tenant-specific JWT via the `serviceToken` function, I already need a JWT as far as I can see. 
Is there no other way to get a JWT on behalf of a certain tenant as it is for the `requestClientCredentials` function mentioned above?

BR 
Tobi

**Comment by nocheintobi** [comment]
Let me ask a little different:
Is the following (which in fact works and corresponds in a way to what is also mentioned in the migration guide) a suitable way to go:
`const token: string = await serviceToken('xsuaa', {jwt: {iss: `https://${tenant}.localhost:8080/uaa/oauth/token`}, useCache: true});` ?

**Comment by FrankEssenberger** [comment]
I think you could just pass a json object with {iss:'',zid:''} to the `serviceToken` method since it doe not really do much with the token. 

I also wonder if the creation of a JWT for Tenant A and then passing it in does and validating it does something from a security point of view. You potentially could just hand in Tenant A in the issuer object.

Nevertheless the creation and validation of a JWT should off course work when the right audiences is theres which potentially is the case for a JWT issued for the XSUAA. When I look at the test in the lib it looks like all app names and client IDs are collected and matched against the audiences:

```
it('ClientId matches token audience without dot', function (done) {
            var token = new Token(["client", "foreignclient", "sb-test4!t1.data.x"]);

            // configures audience validator with client-id from VCAP_SERVICES
            var result = new JwtAudienceValidator("sb-test4!t1").validateToken(token.aud);

            assert(result.isValid()); // should match

            done();
        });
```

So I guess you can also play around with the `requestClientCredentialsToken` and `serviceToken` and see with audience are created.

**Comment by FrankEssenberger** [comment]
> Let me ask a little different:
> Is the following (which in fact works and corresponds in a way to what is also mentioned in the migration guide) a suitable way to go:
> const token: string = await serviceToken('xsuaa', {jwt: {iss: https://${tenant}.localhost:8080/uaa/oauth/token}, useCache: true}); ?

If this leads to a token which can be validated by the lib and you get the destination for the tenant later on, yes. However as I mentioned above this does not add value (not 100% sure there) compared to using the {iss:...} directly in the JWT because you create a token and validate it directly. You still need to ensure that the value for `tenant` is not manipulated by someone. If you have a JWT issued coming from outside of your application this is can not happen

**Comment by nocheintobi** [comment]
Thanks for your input, Frank!
That has helped a lot.
