### ISSUE TITLE
Move from axios to undici as http client

### ISSUE THREAD

**Issue by nazarkulyk** [SAP/cloud-sdk-js#2488]
Currently axios is used as http client abstraction layer.
Much better, standard way would be to use request or fetch way to work over http layer. 
Some standards like 
https://fetch.spec.whatwg.org/
and 
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

So, maybe simple move from axios to [uncidi](https://www.npmjs.com/package/undici) would be good alternative.

https://www.npmjs.com/package/undici

https://undici.nodejs.org/#/

**Comment by marikaner** [comment]
@nazarkulyk That is an interesting idea. We will talk about it, thank you for the suggestion. Can you specify what this would make better for you? Do you have any issues with the current implementation, that you hope to improve with that?

**Comment by nazarkulyk** [comment]
@marikaner undici is developed directly by nodejs dev team. Undici implements standard API, that means you can easy switch this layer to any standard one, specially if you want to go to other platforms. Undici gives you more performance and better HTTP protocol support.

**Comment by FrankEssenberger** [comment]
@marikaner when you have a look keep the boundary condition in mind, that we need to configure proxies which we currently do by handing in the httpProxyAgent instead of the normal httpAgent from node. Same is true for all the trust related certificate things. So these two things need to be supported.

**Comment by FrankEssenberger** [comment]
First [google hit](https://www.scrapingbee.com/blog/proxy-node-fetch/) suggests that you can also pass a custom agent in node fetch. So this should be fine. I would prefer native support though, since our current [agent](https://github.com/TooTallNate/node-http-proxy-agent) is not so active with support. We have a issue with proxy and client side certificate authentication which was not working and not fixed.

**Comment by nocin** [comment]
I would also support this idea, as axios makes problems when using formData ([2450](https://github.com/SAP/cloud-sdk-js/issues/2450)).

**Comment by marikaner** [comment]
@nazarkulyk @nocin Thank you for this suggestion. I created a low priority issue in our backlog to consider such a change in one of our future major version releases. It is not likely that this will happen soon and I currently don't see a good reason to switch.
If this affects you in any way, please let me know, we will reconsider then.
