### ISSUE TITLE
Issue in calling Malware scan service with @sap-cloud-sdk/core 1.54.1 onwards

### ISSUE THREAD

**Issue by krishraheja** [SAP/cloud-sdk-js#2550]
Hi Support,

In my project we are using @sap-cloud-sdk/core 1.54.0. We are having an app for mass upload of documents. Before stating the upload, we are doing a Malware scan of document. I was working fine with 1.54.0.

Sometime back I upgraded it to 1.54.1 due to some whitesource vulnerability and with that it started to raise the timeout issue which we had provided in parameters of Malware scan call.

Today I tried with 1.54.2 but same issue is coming. Then I reverted it to 1.54.0 and it is working fine.

Can you help in resolving this issue in next release of @sap-cloud-sdk/core.

In case if you need more details, we can speak on our internal teams chat.

Best Regards
Krishan Raheja

**Comment by florian-richter** [comment]
Hi Krishan, version 1 of the SAP Cloud SDK is deprecated. You should upgrade to version 2. We wrote a guide to help you with the process: https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-2

Please re-open the ticket or create a new ticket if the same issue occurs with version 2.4.0 or newer.

**Comment by krishraheja** [comment]
Hi Florian,

We have applied the changes as suggested in documentation, and our API calls are working fine as were working earlier.

But the issue for which I raised this issue, is still occuring.

We have setup a Destination in CF provider account and in .cdsrc.json we have added in required section like below:

    "MalwareScanner": {
      "kind": "rest",
      "credentials": {
        "destination": "MALWARE_SCANNER",
        "url": "https://malware-scanner.cf.sap.hana.ondemand.com",
        "requestTimeout": 30000
      }
    },


We care calling it through cds.connect.to method as below:

  public static async scan(data: any, req: any) {
    const malwareScan = await cds.connect.to('MalwareScanner');
    const result = await malwareScan.tx(req).post('/scan', data);
    console.log(result);
    return result;
  }

But when executing this, we are getting timeout error(30 seconds as mentioned in .cdsrc.json) file.

This implementation is working fine in @sap-cloud-sdk/core 1.54.0 and in the following releases it is not working even in version 2.

In case if you need further assistance, please feel free to reach me on our internal teams.

Best Regards
Krishan Raheja

**Comment by florian-richter** [comment]
From our internal conversation:

Hey Krishan, 
I investigated your issue. 

You state that it works with core@1.54.0 but not with core@1.54.1 or 1.54.2. This seems very strange to me as 1.54.1/1.54.2 ONLY add/remove a message to the postinstall script of the package. There are no functional changes at all. This let's me believe there is another underlying issue which causes your timeout.

Could you verify that it is the version change in the SDK that causes this error? Since you don't have a lock file (package-lock.json or yank.lock) there may be undetected changes when you install because you use the ^ prefix to versions (which allows minor and patch changes automatically).

The code you point to has (as far as I can tell) no direct interaction with SDK code and CAP uses a fixed version of the SDK behind the scenes, so the version you install in your project does not impact CAP.

Best regards
Florian

**Comment by florian-richter** [comment]
You could do the following to verify if this is actually is an SDK issue or help you point into the right direction to solve the issue:
- Debug the call and check if any SDK methods are called --> step into the CAP code or add breakpoints in the relevant functions in core (if v1) or connectivity (if v2)
- Run `npm ls --all` with 1.54.0 and 1.54.1 --> check the list for differences and consider fixing the versions of packages that changed unintentionally between the two installs
