### ISSUE TITLE
How to generate a service using generate-odata-client from an ECC or S4 using the service's $metadata?

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SAP/cloud-sdk-js#2556]
I'm trying to convert a $metadata into a service for use with the sap cloud sdk lib.

`generate-odata-client --inputDir .\ctradeslipdata_metadata.xml --outputDir tradeslipdata`

Error

```
[2022-06-10T01:36:13.788Z] ERROR    (generator-cli): ErrorWithCause: Generation of services failed.
    at C:\Users\Avell\AppData\Roaming\nvm\v14.17.0\node_modules\@sap-cloud-sdk\generator\dist\generator-cli.js:22:18
Caused by:
Error: EEXIST: file already exists, mkdir 'D:\PESSOAL\PROGRAMACAO\JS\nest\exemplo-api-btp\ctradeslipdata_metadata.xml'
```

estruct

```
d----             dist
d----             node_modules
d----             src
d----             test
d----             tradeslipdata
-a---          77 .env
-a---          20 .eslintignore
-a---         681 .eslintrc.js
-a---          49 .gitignore
-a---          51 .prettierrc
-a---       62594 ctradeslipdata_metadata.xml
-a---        5742 default-env.json
-a---         443 manifest.yml
-a---         220 nest-cli.json
-a---        3107 package.json
-a---          97 tsconfig.build.json
-a---         581 tsconfig.json
-a---      317412 yarn.lock
```

**Comment by luizcarlospedrosogomes** [comment]
create path 'services'
move ctradeslipdata_metadata.xml to path services
`generate-odata-client --inputDir ./services/ --outputDir ./src/services`

**Comment by luizcarlospedrosogomes** [comment]
but 
```
D:/PESSOAL/PROGRAMACAO/JS/nest/exemplo-api-btp/node_modules/@sap-cloud-sdk/util/dist/fs.d.ts:1:22 - error TS2688: Cannot find type definition file for 'node'.
D:/PESSOAL/PROGRAMACAO/JS/nest/exemplo-api-btp/node_modules/winston-transport/index.d.ts:1:241 - error TS2688: Cannot find type definition file for 'node'.
D:/PESSOAL/PROGRAMACAO/JS/nest/exemplo-api-btp/node_modules/winston/index.d.ts:1:111 - error TS2688: Cannot find type definition file for 'node'.
D:/PESSOAL/PROGRAMACAO/JS/nest/exemplo-api-btp/node_modules/winston/lib/winston/config/index.d.ts:1:111 - error TS2688: Cannot find type definition file for 'node'.
D:/PESSOAL/PROGRAMACAO/JS/nest/exemplo-api-btp/node_modules/winston/lib/winston/transports/index.d.ts:1:111 - error TS2688: Cannot find type definition file for 'node'.
    at transpileDirectory (C:\Users\Avell\AppData\Roaming\nvm\v14.17.0\node_modules\@sap-cloud-sdk\generator\node_modules\@sap-cloud-sdk\generator-common\dist\compiler.js:35:15)
```

**Comment by jjtang1985** [comment]
Hi @luizcarlospedrosogomes ,

Thanks for raising this up.

I'm happy that you solved the first issue (`file already exists`) by your own, which is correct, as `--inputDir` expects a directory path instead of a file path.
Here you can find the [complete documentation](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-odata-client#options) of the generator.

For the second issue (`TS2688: Cannot find type definition file for 'node'`), this happened when transpiring the generated TypeScript client to JavaScript client.

Cloud you please share the following information:
- the `package.json` and the `tsconfig.json` shown in the description
- I assume you use node `14.17.0` as I saw it
- `npm` version
- `ts-node` version
- `typescript` version

Best regards,
Junjie

**Comment by jjtang1985** [comment]
Hi @luizcarlospedrosogomes ,

we haven't heard you for a while.
Would you like to share more details?

Best,
Junjie

**Comment by marikaner** [comment]
Hey @luizcarlospedrosogomes, we investigated this issue and for the time being we recommend to install the generator as a dev dependency. Please try this instead.
