### ISSUE TITLE
Retrieved destination doesn't contain authTokens

### ISSUE THREAD

**Issue by thisisevanfox** [SAP/cloud-sdk-js#2558]
Hello all,

since I upgraded the @sap-cloud-sdk package from 1.53.x/1.54.x to 2.4.0, I'm facing the issue that retrieved destination does not include any authTokens although the forwardAuthToken property is set to true.

To clarify the problem, I have attached code and screenshots below of how the application behaved before and after the upgrade.

I am not sure if this is really an issue or if the behaviour is so desired. I wanted to report the behaviour anyway to find out if I am doing something wrong. If the behaviour is as desired as described below, can you tell me what I'm doing wrong or what I need to do differently to get authTokens with the destination?

Kind regards
Johannes
______________________

### Definition of destination in "User-Provided Variables" in the BTP
```
[ {
     "forwardAuthToken" : true,
     "name" : "myDestination",
      "url" : "https://<my-url>.cfapps.eu10.hana.ondemand.com"
} ]
```

### Old behaviour
Used: version: `"@sap-cloud-sdk/core": "1.53.1"`

Calling the `getDestination` method:
```
	import * as coreCloud from "@sap-cloud-sdk/core";
	[...]
        const foundDestination = await coreCloud.getDestination("myDestination", {
             userJwt: <valid-user-token>,
             useCache: true,
	});
	[...]
```
**Response:**
![image](https://user-images.githubusercontent.com/43059689/173042003-475e89fb-d116-43c1-b4f9-24216c6f964c.png)

As you can see authTokens array is filled.

### New behaviour
Used: version: `"@sap-cloud-sdk/connectivity ": "2.4.0"`

Calling the `getDestination` method:
```
	import * as connectivityCloud from "@sap-cloud-sdk/connectivity";
	[...]
        const foundDestination = await connectivityCloud.getDestination({
             destinationName: "myDestination",
             jwt: <valid-user-token>,
             useCache: true,
	});
	[...]
```

**Response:**
![image](https://user-images.githubusercontent.com/43059689/173041882-fdf1e972-5881-4058-be99-8b0196aa6246.png)

As you can see authTokens array is not filled.

###  My finding
I debugged the sources of the two versions of the sdk. And it looks like that the part where the authTokens are added to the destination is not implemented in the new version.

**Old implementation**
![image](https://user-images.githubusercontent.com/43059689/173044179-3e65a9d0-aae5-4377-a528-12a8694d58de.png)

**New implementation**
![image](https://user-images.githubusercontent.com/43059689/173044262-a61e41cf-686b-44d9-96c6-05025e526fb6.png)

**Used Versions:**

- node version: `v14.19.2`
- npm version: `6.14.17`
- SAP Cloud SDK version:  `"@sap-cloud-sdk/connectivity ": "2.4.0"`

**Comment by FrankEssenberger** [comment]
Hello @thisisevanfox,

thanks for the issue and the evaluation work you put into it. You have found a not well documented change from our side. I think we mentioned it in the migration guide but not explicit enough and this is also a bit like the hitch hiker guide - who looks at release notes....

Anyway let me explain the situation. We introduced a new method called [registerDestination](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination#register-destination-via-the-sap-cloud-sdk) which provides a proper cache and isolation strategy based on the provided user JWT. This was not the case for the environment variable destination before. This method is also still present, but meant for testing only. 

Since the `registerDestination` was the thing to in production, the logic for [forwarding auth tokens](https://github.com/SAP/cloud-sdk-js/blob/main/packages/connectivity/src/scp-cf/destination/destination-from-registration.ts#L81) was moved to this method.

I hope you can use the `registerDestination()`method instead. Also note that the `useCache` option is only relevant when you get destination from the service. 

Best
Frank

**Comment by thisisevanfox** [comment]
Hi @FrankEssenberger,

thank you for the quick response. I read through the links you provided, but - to be honest - I'm not really sure where to put the call for the `registerDestination`.

To give a little insight into the coding: Like mentioned above the destinationations are stored in the environment variables which are filled by the mta deployment. With the old version of the sap-cloud-sdk we fetched the destination with `getDestination`. After getting the destination we took it and did a `executeHttpRequest`.

With the new version of sap-cloud-sdk I just changed the packages and ran in issue that the authTokens are missing in the fetched destination so the `executeHttpRequest` call fails.

Questions which came to my mind when reading through the documentation:

- Where to call `registerDestination`? Right before calling `executeHttpRequest` or maybe once at server start?
- After calling `registerDestination` do I still ned to call `getDestination` and pass the fetched destination to `executeHttpRequest` or is there some kind of method like `getRegisteredDestination` and pass this object to `executeHttpRequest` ? What to pass to `executeHttpRequest` ?

I already tried to call `registerDestination`, after that I called `getDestination`. Unfortunately authTokens still was empty. So I think I messed something up.

Can you help me out to get rid of my confusion?

Kind regards
Johannes

**Comment by FrankEssenberger** [comment]
Good morning @thisisevanfox,

here my first thoughts:

- _Can you help me out to get rid of my confusion?_ The registerDestination adds the destination to a key value store or cache if you want to call it that way. When you call then `getDestination` it will look at the env variable first, then the register destination cache and last the actual destination service. When a destination with the given name is found the flow is stopped and the result is returned. In the latest security validation it was pointed out that it is not a good practice to store destinations in environment variables because people could store too sensitive information in the environment. Therefore we introduced the register method and the env is stell there, but really meant for local test purpose.
- _Where to call registerDestination?_ Once at server start should be fine and you must do it before the first `getDestiantion` or `executeHttpRequest` call.
- _After calling registerDestination do I still need to call getDestination_ The `executeHttpRequest` does a lookup (calls `getDestination`) of the destination if you provide the [DestinationFetchOption](https://github.com/SAP/cloud-sdk-js/blob/df141239c0b1fece5268a050b4b9c5c614cf8650/packages/connectivity/src/scp-cf/destination/destination-accessor-types.ts#L72) with the name of the registered destination. So you can directly use: `executeHttpRequest({destinationName: 'nameOfRegisteredDestination', jwt: 'myJwtToPropagate')`

I hope this helps.

Best
Frank

**Comment by thisisevanfox** [comment]
Hi @FrankEssenberger,

thank you for the clarification. I removed the destination definition from our environment variable, registered it and called `executeHttpRequest` - now it works.

One last question:
As I don't have an user jwt at server start, I need to register the destination right before `executeHttpRequest` - there the token is available. Now, whenever a `executeHttpRequest` is called `registerDestination` is called too. I wonder if this is a problem in the feature since the js doc of `registerDestination` says an error is thrown when the destination already exists? Right now there is no error and `executeHttpRequest` is called correctly afterwards.

Quote from ts doc of  `registerDestination`:
> Throws an error if a destination with the same name as the given test destination already exists.

To make sure that the call of `registerDestination` is not in vain, I could use the `searchRegisteredDestination` to check if the destination is already registered. But I don't know if this is necessary.

Kind regards
Johannes

**Comment by FrankEssenberger** [comment]
I just had a look at the code and I do not see an error if the destination already exists. I guess this should be removed -> wrong doc.

If you call it without a JWT, the tenant id from the provider account (the one where the application is hosted) is used to build the cache key. This should be fine in most cases.

If you have a multi tenant situation where you would perhaps loop over all subscribed accounts at application startup and register all the destination from these accounts,  you would need to pass a JWT to have the right cache key. Since the JWT is not verified you can simply pass a token containing the `zid` property. This is the field from where the tenant is identified.

Best
Frank

**Comment by thisisevanfox** [comment]
Thank you very much, the issue is now solved for me. For other users, I think it would be helpful if the registration of destinations was better documented. How you deal with the issue is up to you - close it or leave it open for documentation. Thanks again for the support.

Kind regards
Johannes

**Comment by FrankEssenberger** [comment]
Thanks for the feedback. I close it and create a back log item to improve documentation.
