### ISSUE TITLE
connecting S4 Hana system to node.js application

### ISSUE THREAD

**Issue by nishnp** [SAP/cloud-sdk-js#2803]
I am trying to connect Nodejs application to S4 Hana system. But, I am not able to do it I wrote the code something like this.
![image](https://user-images.githubusercontent.com/62622069/186681835-775c6f65-7c62-4d29-a57d-30908eefa389.png)
I am getting the error like this.
![image](https://user-images.githubusercontent.com/62622069/186681892-85c134ca-a509-4651-9965-1b259848e29c.png)
It gives Unauthorized error, I bound the below service.
![image](https://user-images.githubusercontent.com/62622069/186681976-1fa7d103-36ad-421e-b612-59c612ab2ac0.png)
Please let me know a way to connect to S4 Hana instance with Node.js(I am not using a CAP Application) Application

**Comment by fwilhe** [comment]
Hi @nishnp 

it looks like you're using the [generic http client](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/generic-http-client) of the sdk and don't provide any authentication means.

Since you are interacting with an oData service, I'd recommend using the [oData](https://sap.github.io/cloud-sdk/docs/js/features/odata/execute-odata-request) client provided by the SDK. This should use the authentication information provided by your destination automatically.

Please let me know if this solves your problem,
Best regards,
Florian

**Comment by FrankEssenberger** [comment]
@nishnp also the generic client should add all auth headers. This issue seems similar to this one:

https://github.com/SAP/cloud-sdk-js/issues/2770

Since the error is 401 there is something wrong with the credentials:
- If the authentication type of the destination is `PrincipalPropagation` a JWT must be added as shown [here](https://github.com/SAP-samples/cloud-sdk-js/blob/main/samples/cf-sample-application/src/principal-business-partner/principal-business-partner.service.ts) - but from the logs it looks like basic.
- Check if the username and password are correct and the user is not locked in the system.
- You can also have a look at the http logs of the target system and investigate why the system is returning 401. 

Please also note that the screenshot you provided contains the basic header send to the system so the user and password should be changed :-).

**Comment by FrankEssenberger** [comment]
Since this is the second issue regarding this topic I also checked and the nightly tests for version 1, 2 and canary are green testing this use case E2E - also my manual test just a minute ago worked for basic and principal propagation as well.

**Comment by nishnp** [comment]
I tries using the odata client provided by sdk something like this
![image](https://user-images.githubusercontent.com/62622069/186786603-d8a289f2-359f-486b-8856-6abc386f9d23.png)
code is something like this 
![image](https://user-images.githubusercontent.com/62622069/186786638-50812bf1-fbac-4aba-acf1-00965e757014.png)
![error1](https://user-images.githubusercontent.com/62622069/186786819-f66e68b9-8445-4aa2-a720-bb1cab67c3bb.png)
I see that the Authorization takes my correct credentials. It would be great if you could help me.

**Comment by FrankEssenberger** [comment]
As discussed in a direct call perhaps try to setup a business application studio instance make the the "curl" test as dicribed in our documentation to rule out the SDK as a reason.

**Comment by nishnp** [comment]
Hi... Using the cloud SDK of a business partner worked for me.
![image](https://user-images.githubusercontent.com/62622069/188125869-17dbd22b-80cc-41af-a4ac-b2fe5483ea47.png)
the only error I was making was I did not add await before the request.
![image](https://user-images.githubusercontent.com/62622069/188126025-0c4caf29-a303-4334-b2eb-ac39dfe84a70.png)
That works for me... thanks for the help though @FrankEssenberger and @fwilhe
