### ISSUE TITLE
Error during request to remote service: \nRequest failed with status code 415

### ISSUE THREAD

**Issue by krishraheja** [SAP/cloud-sdk-js#2847]
**Describe the bug**
When doing a scan from my code, ""Error during request to remote service: \nRequest failed with status code 415" is started coming, it was working fine before.

We have a CDS entity whose field content is defined with LargeBinary data-type. Our app was released in 2111 and from that time, it was working fine. But now issue is coming while doing Malware scanning. Code snippet is as below:

![image](https://user-images.githubusercontent.com/53295200/188853638-cb58b424-87f1-4fc4-afae-a65b2966cb55.png)

**Expected behavior**
Malware scan should accept values from LargeBinary data-type field.

**Screenshots**
![image](https://user-images.githubusercontent.com/53295200/188853777-ccc491f2-77c5-4635-adf3-f2e334549ce1.png)

**Used Versions:**

- node version via `node -v`  16.17.0
- npm version via `npm -v`     8.15.0
- SAP Cloud SDK version you used as dependency    
    "@sap-cloud-sdk/core": "1.54.0",
    "@sap-cloud-sdk/http-client": "^2.4.0",
    "@sap/cds": "^6.0.1",
    "@sap/cds-dk": "^6.0.1",
    "@sap/cds-mtx": "^2.5.3",

**Impact / Priority**        High priority

Affected development phase: e.g. Getting Started, Development, Release, Production   Customer Testing, initial Release happened in 2111

Impact: e.g. No Impact, Inconvenience, Impaired, Blocked       Blocked for customer testing

In case if you need further information, please contact through our internal teams chat at krishan.raheja@sap.com

Best Regards
Krishan Raheja

**Comment by jjtang1985** [comment]
Hi @krishraheja ,

Thanks for raising up.

> SAP Cloud SDK version you used as dependency
"@sap-cloud-sdk/core": "1.54.0", // sdk
"@sap-cloud-sdk/http-client": "^2.4.0", // sdk
"@sap/cds": "^6.0.1", // cds
"@sap/cds-dk": "^6.0.1", // cds
"@sap/cds-mtx": "^2.5.3", // cds

I see you listed some `cds` dependencies as SDK dependency, which is not the case.
Please contact the cds team [here](https://cap.cloud.sap/docs/resources/).

Also, please use the same major version for all SDK dependencies.
Mixing them might cause some issues.
FYI, the version 1 SDK is deprecated, consider using SDK version 2 is preferred.

**Comment by FrankEssenberger** [comment]
I would close this issue because it is not a SDK issue. Please reach out to the CAP colleagues. As some hint I would try to either get some http logs to see what CAP is actually sending as a request causing the 415 error OR
use some low level http client (axios, node-fetch....) to see if it is working in principal. Perhaps the API of your target malware scanner endpoint has changed? 

In case you have a minimal example using the `http-client` of the SDK making a request showing some bugs please reopen the issue. 

Best
Frank

**Comment by johannes-vogel** [comment]
Hi @FrankEssenberger and @jjtang1985,

I had another look into this issue and I observed the following behavior:

For the mentioned POST request, CAP generates the following request config:

![Screenshot 2022-09-12 at 10 54 45](https://user-images.githubusercontent.com/31311694/189613622-c5481af0-a5af-4d23-90d4-120f73081132.png)


Please note that `content-type` header is not set.

In the error object, I can see that the following config was used:

![Screenshot 2022-09-12 at 10 56 04](https://user-images.githubusercontent.com/31311694/189613840-4cd8698b-78c6-4044-8f0f-eca8fe7036d1.png)

Please note the `content-type` header set by the SDK.
The malware scan API expects the content-type header to be set to `application/octet-stream`. If I set that manually, the request works.

With CDS 5 and SDK V1 the following is send by CAP and the SDK:

![Screenshot 2022-09-12 at 11 15 01](https://user-images.githubusercontent.com/31311694/189617691-d0ddd6e0-1f57-485e-ab18-9c9cf846e90a.png)

In that version, the content-length and content-type is not set correctly. This is fixed by CAP in the meanwhile.
![Screenshot 2022-09-12 at 11 16 07](https://user-images.githubusercontent.com/31311694/189617922-abadc407-be18-4b38-9c0b-1b5f774b6a3d.png)

In the eventually used config, I can see that the SDK calculated the content-length correctly, but also uses `application/json` as content type. That might worked by coincidence in the past.

As per [API documentation](https://api.sap.com/api/MalwareScanAPI/resource), `application/octet-stream` should be used.


From my point of view, CAP uses the right config now, but I wonder why the SDK adds the `content-type: application/x-www-form-urlencoded`. Could you please double check?

**Comment by FrankEssenberger** [comment]
Hi @johannes-vogel,

thanks for providing the request details so that we can get an idea what went wrong. Just as a first clarification we do not set the Content-Type header or length. This is done by the low lying http-agent which is axios in our case. There is one exception to this rule. For OData request we set the content type to JSON which is ok since OData API must accept JSON or some XML I guess.

So the value `application/x-www-form-urlencoded` you started seeing after the update is just the [default value](https://github.com/axios/axios#global-axios-defaults) from axios. I guess this is a good default for post request because it will work in most cases. 

Since for the specific API Johannes found that the value must be `application/octet-stream`, @krishraheja you must set this on the request level. I do not know how to pass custom headers to the req using the `.tx()` call but Johannes knows this for sure. In case this is not possible you can have a look at the axios API how to adjust this globally or for the next call via the axios scope bypassing the CAP and SDK API, which is not nice, but a workaround in such a case.

I also assume the API you were calling was getting more strict recently, because in the past the header was set accidentally via CAP to `application/json` which was accepted. Now, another wrong header  value is not accepted. Anyway, as I said the correct way to do it is to specify the header explicitly.

Best
Frank

**Comment by johannes-vogel** [comment]
@FrankEssenberger Thanks for clarifying!
