### ISSUE TITLE
Class constructor RequestBuilder cannot be invoked without 'new'

### ISSUE THREAD

**Issue by robbymanis** [SAP/cloud-sdk-js#2968]
**Describe the bug**
RequestBuilder cannot be invoked without `new`. 

**To Reproduce**
Generate an odata client following the [getting started](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-odata-client) guide and after `tsc` trying to run the script will result in the following error:

**Expected behavior**
Be able to use the generated RequestBuilder class.

**Screenshots**
![image](https://user-images.githubusercontent.com/87324087/196287611-0a842068-23c5-4fde-a733-880846ece75e.png)
**Used Versions:**

- node version via `node -v` v16.17.0
- npm version via `npm -v` 8.15.0
- SAP Cloud SDK version you used as dependency @sap-cloud-sdk/generator": "^2.9.0"

**Code Examples**
If applicable, add code snippets as examples to help explain your problem. Please remove sensitive information.
**tsconfig.json**
```json
{
   "compilerOptions":{
      "target":"ES2016",
      "module":"commonjs",
      "esModuleInterop":true,
      "forceConsistentCasingInFileNames":true,
      "strict":true,
      "skipLibCheck":true
   }
}
```

**Log file**

```log
[2022-10-17T21:28:08.958Z] ERROR    TypeError: Class constructor RequestBuilder cannot be invoked without 'new'
    at new FlightRequestBuilder (C:\SAPDevelop\robby_report\srv\services\rmtsampleflight-service\FlightRequestBuilder.js:27:42)
    at FlightApi.requestBuilder (C:\SAPDevelop\robby_report\srv\services\rmtsampleflight-service\FlightApi.js:40:16)      
    at Object.<anonymous> (C:\SAPDevelop\robby_report\srv\index.js:5:11)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

**Impact / Priority**

Low priority. 

Affected development phase: Getting Started

Impact: Inconvenience

Timeline: No timeline

**Additional context**

**Comment by marikaner** [comment]
Your code looks correct, this might in fact be a bug. We will investigate and come back to you soon.

**Comment by FrankEssenberger** [comment]
I have a quick try to reproduce the error. I know the error message from cases when you set the [target to low](https://bobbyhadz.com/blog/typescript-class-constructor-cannot-be-invoked-without-new#:~:text=The%20%22Class%20constructor%20cannot%20be,new%20operator%20when%20instantiating%20classes.). However ES2016 should be fine.

**Comment by FrankEssenberger** [comment]
Hello @robbymanis,

I had a quick look and I could not reproduce the issue. When I look at my generated `.ts` code I see in the request builder the `new` keyword:

![image](https://user-images.githubusercontent.com/56544999/196401803-3d4b814a-74a7-447b-afd4-a675018319ac.png)

In the transpiled `.js` it then also shows up as expected (independent of the chosen runtime since it is explcitly there):

![image](https://user-images.githubusercontent.com/56544999/196401976-d6e75e03-07e7-47a0-a729-9e57a376f325.png).

If I remove the `new` keyword in my code I can reproduce your error, but the question is I guess why you get different code generated.

Could you perhaps check your generated sources and see if the `new` keyword is in the sources? Perhaps you have a version of the generator installed globally. Cloud you in your repo execute ` npx generate-odata-client --version` and see if it is really `2.9.0` and ensure the same `npx` command is used for generation.



Best
Frank
