### ISSUE TITLE
Proxy-Authorization header for on-premise MAIL destination in java 

### ISSUE THREAD

**Issue by mvmanov** [SAP/cloud-sdk-js#2983]
Hi colleagues,
 In the node.js version of the SDK I am able to retrieve the proxy-authorization headers from an on-premise destination of type MAIL, but with the java version as far as I can see the decoration with the additional headers is available only for http destinations (com.sap.cloud.sdk.cloudplatform.connectivity.ScpCfHttpDestination.canDecorate(DestinationProperties)).
 It would be convenient for me if I can retrieve those headers or the jwt token for connectivity either as part of a destination or as a separate API.
 I am using the Cloud SDK within an app on CF.

Thank you,
Milen

**Comment by newtork** [comment]
Hi Milen,

* Can you please motivate your use case for the Mail destination to OnPremise on your Java runtime?
* At what point do you plan to add/use headers? Where do you _put_ the destination once resolved?

An unchecked workaround could be:
```java
final Option<List<DestinationAuthToken>> tokens = destination.get("authTokens", o -> (List<DestinationAuthToken>) o);
```

**Comment by MatKuhr** [comment]
Hi Milen, could you please share how you configured the destination in the BTP cockpit? In particular, I am curious which authentication type you are using, if any.

The workaround above would in any case only yield the authorization token, but not the proxy headers. Another approach might be to define an additional "normal" HTTP destination pointing to the same on-prem system. Then retrieving that and getting the headers from it should yield both authorization and proxy headers.

Of course that is not ideal, but may be an improvement for the moment. Because right now we don't have a mail client on the Java side and thus don't natively support the authentication type.

**Comment by jjtang1985** [comment]
Hi @mvmanov ,

I know it's probably a bit late, but this repository is for the SAP Cloud SDK for JavaScript.
I created an issue [here](https://github.com/SAP/cloud-sdk/issues/1093).

@newtork , @MatKuhr , FYI, the user provided more details about the use case.
