### ISSUE TITLE
 Create request failed!

### ISSUE THREAD

**Issue by ELBEQQAL94** [SAP/cloud-sdk-js#3015]
**Describe the bug**
After I migrated to client V2, When I want to create a request builder response failed with `Create request failed`

My Code: 

``` js
sendOrderCreation: async (salesOrders: SalesOrders, csrfData: SessionInformation): Promise<SalesOrders> => {
    logger.info(`CRSF token retrieved: csrfToken: ${csrfData.csrfToken}`);
    logger.info(`Parsed cookies: parsedCookies: ${csrfData.cookies}`);

    logger.info(`Calling ERP to create order with requestbuilder: ${Config.erp.serviceHost}, Sales order object:`, salesOrders);
    const requestBuilder = salesOrdersApi.requestBuilder()
      .create(salesOrders)
      .addCustomHeaders({ 'X-CSRF-Token': csrfData.csrfToken, cookie: csrfData.cookies });

    logger.info('Request builder data to be sent to ERP: requestBuilder:', requestBuilder);

    return requestBuilder.execute({
      name: 'sales-order',
      url:Config.erp.serviceHost,
      isTrustingAllCertificates: true,
    });
  },
```

Test code:

``` js
it('should resolve call to create order in erp if it succeeds', async () => {
        const salesOrderMock = createSalesOrder(backofficeOrderMock, '');
        await expect(erpService.sendOrderCreation(salesOrderMock, csrfData)).resolves.toBe(salesOrderMock);
    });
```

Result:

` Received promise rejected instead of resolved
    Rejected to value: [ErrorWithCause: Create request failed!]`

Someone can help me!

Thanks

**Comment by jjtang1985** [comment]
Hi @ELBEQQAL94 ,

Thanks for raising up.

From the given error message `Create request failed`, the root cause it not clear, could you please share it?
Here is the [documentation](https://sap.github.io/cloud-sdk/docs/js/features/error-handling) for retrieving the root cause.

If the root cause is an axios error, please check this [section](https://sap.github.io/cloud-sdk/docs/js/features/error-handling#debug-axioserror).

On the other hand, you mentioned you switched to v2, could you please also share the previous status?
Did your code with the SDK v1 work?
If yes, maybe also share the working code snippets?

Thank you.

**Comment by marikaner** [comment]
Hey @ELBEQQAL94, this issue didn't have activity in a long time, so I'll go ahead and close it. I hope you were able to resolve your issue.
