### ISSUE TITLE
Random 502 Failed to load destination. Caused by: Failed to fetch destination ... Caused by: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by piejanssens** [SAP/cloud-sdk-js#3019]
```
Random 502 Failed to load destination. Caused by: Failed to fetch destination <sf-end-user>. Caused by: getaddrinfo ENOTFOUND destination-configuration.cfapps.eu30.hana.ondemand.com
```

That looks like some sort of hostname resolution error, right?

This occurs seemingly at random. The destination exists and works fine most of the time.
I don't know where to start to get to the bottom of this issue... help is appreciated 😄

**Comment by jjtang1985** [comment]
Hi @piejanssens ,

Thanks for raising up.

The random behaviour seems to be related to the flakiness of the destination service.
For that, I recommend that you can create an incident to the destination service [here](https://support.sap.com/en/index.html).

From the SDK perspective, here you find a similar [issue](https://github.com/SAP/cloud-sdk-js/issues/2806) due to the flakiness and my answer [using cache](https://github.com/SAP/cloud-sdk-js/issues/2806#issuecomment-1233868359) helped.

You can find our documentation regarding cache and the isolation strategy [here](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination-cache#destination-service-cache).

Let me know if you have questions.

**Comment by piejanssens** [comment]
Since both issues are concerning SFSF, it might be an issue with the token service of SFSF.
We need to see what the /oauth/token request is returning to the destination service.
Is there a possibility you can raise this internally? AFAIK, the destination service is like a black box, without tracing options.

**Comment by piejanssens** [comment]
Incident created: 803167 / 2022

**Comment by jjtang1985** [comment]
Hi @piejanssens ,

Thank for for creating an incident.
Sure, we will forward your feedback via internal channels.
@marikaner, yet another case related to destination service/SFSF.

On the other hand, have you tried the cache or do you have questions regarding the cache?

**Comment by piejanssens** [comment]
Hi @jjtang1985,

Today, I was able to reproduce the issue (CAP service running locally on macOS - NodeJS v16.14.2) after 30 application refreshes. 

Destination service engineer confirms there are no errors that can be seen from their side (all 200's).
This would indeed be expected if the error is correct as the ENOTFOUND indicates a name resolution issue that occurs on the client (CAP service in this case) side and would stop the request from ever reaching the host.

This narrows it down to a DNS server, axios, NodeJS or OS level name resolution error?

**Comment by piejanssens** [comment]
Interesting article on Node, caching DNS requests and expecting OS to handle the cache: https://medium.com/@amirilovic/how-to-fix-node-dns-issues-5d4ec2e12e95

**Comment by jjtang1985** [comment]
Hi @piejanssens ,

Thanks for sharing the the knowledge 👍 

We had an internal discussion regarding the your proposal of the dns cache, and here are some summary:

1. If dns cache can solve the issue, the destination cache can also do the same, which is even more powerful, because it covers both dns and the real requests. Therefore, we would still recommend using the destination cache.
2. Unfortunately, you mentioned using CAP made it more complicated and CAP did not expose the destination cache option. We will forward your message to CAP. Also, even if we integrate the dns cache, if CAP does not expose, it's the same as the destination cache.
3. We are currently working on the next major version, and a middleware topic is one of new feature. Basically, you can provide your own middleware typically for resilience topics. Please check this [ADR](https://github.com/SAP/cloud-sdk-js/blob/main/knowledge-base/adr/0031-resilience-options.md) for details.

**Comment by jjtang1985** [comment]
Hi @piejanssens ,

> Unfortunately, you mentioned using CAP made it more complicated and CAP did not expose the destination cache option. We will forward your message to CAP

I got a quick reply from our CAP colleagues, and here is the CAP [doc](https://pages.github.tools.sap/cap/docs/guides/using-services#use-destinations-with-nodejs) describing how to pass the destination options to the SAP Cloud SDK.
If you have further questions about CAP, maybe consider approaching CAP directly.

**Comment by piejanssens** [comment]
Do you have a public URL for this information?

**Comment by jjtang1985** [comment]
Sorry for just copy/pasting the answer from the colleague. I updated the link in the previous post. Please have a look.

**Comment by piejanssens** [comment]
Thanks @jjtang1985 

I wasn't sure it was working at first as I was thrown off by "registered destinations" instead of "cached destinations", but then I traced down the logging statement to confirm the destinations were being read from the cache.

> "Successfully retrieved destination 'sf-end-user' from registered destinations."

Initial signs are positive! 

```
  "cds": {
    "requires": {
      "uaa": {
        "kind": "xsuaa"
      },
      "SF_REST": {
        "kind": "rest",
        "credentials": {
          "destination": "sf-end-user",
          "requestTimeout": 30000
        },
        "destinationOptions": {
          "useCache": true
        }
      }
}
```

I will close this issue for now. 

It might be worth considering enabling this by default and until then, reference the option from the CAP documentation.
