### ISSUE TITLE
Destination-Cache: Reduce "expiresIn" on purpose before caching the destination

### ISSUE THREAD

**Issue by drvup** [SAP/cloud-sdk-js#3315]
Hi SAP Cloud SDK Team,

I have a feature request for the SAP Cloud SDK.

I am using the SDK Cache for destinations on my applications to store destination-details incl. authTokens to not have to reach-out all the time to the destination service.
I know, the destination-service is in charge to fetch a new token before it's expiring. The destination-service is doing that some minutes before it does expire. 
The logic implemented on the SDK is about converting the "expiresIn" seconds to milliseconds and add it to the Date.new() / timestamp-now - so it's not expiring earlier then it should be - it will expire right at the time it has to. That's fine and does work.

But if I fetch the destination first, save it to a constant, prepare the request to the destination-target and fire it afterwards, some time (seconds) is already gone. Any I do guess this is resulting in 401 http status on the destination-targets I can see on the log.

My application is an express application and is getting called by the Job-Scheduler-Service of the BTP all X minutes.
The route / process will take something like 1minute to fulfill the request (It's about fetching employees from A, saving to B and sending some logs to C). Whatever, I investigated some issues sometimes (Once / Twice a week), where I do run into http-status 401 on the target of the application. This happens, because the token is not valid anymore (expired). So I checked the logic and implementation and I am really sure it's about the cache. The logic sets the exact time as expiration time for the auth token - so there is no delay added on purpose.

**Describe the solution you'd like**
Option A)
Adding a coming out-of-the-box developer- / application-friendly-delay (3min?!) reduced from the expiration time on purpose before adding to the cache ( scp-cf / destination / destination-cache.ts > cacheRetrievedDestination )

Option B)
Having the opportunity to manually add a delay to the destination before added to the cache

Option C) 
The .execute() / request-builder-base.ts > build() function does check the expiration of an authToken before sending each request.

**Describe alternatives you've considered**
The alternative for me is about loading the destination to a later stage. Maybe with SDK v3 I can inject / extend the .execute() request with some manual destination-fetch approach in a middleware ;-)
Another idea is about checking the expiresIn value on my "getDestination" / "initialize" methods on my own. 

**Impact / Priority**
This is not critical, it's just a useful feature request about a scenario I did run into multiple times.

Thanks for the great work and the really cool SDK - it's helping a lot and did speed up implementation times a lot!
Really looking forward for v3!

Kind regards,
Cedric

**Comment by FrankEssenberger** [comment]
Hi @drvup,

I read over the issue and I am not 100% sure if I got it to be honest. Anyhow I have some idea :-). One thing to try could be our custom [cache function](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination-cache#custom-destination-service-cache). We introduced this for users who have a big K8s application and wanted to use a redisDB to store the destinations so that all pods can benefit from the central shared cache outside of a single node process. However, this involves a custom implementation and if you mess something up with the cache keys this is immediately security relevant.

Alternatively I was wondering why you store the destination in a variable and use it later. If you have the cache, just pass the options to fetch it again later. It will check the cache again with the `expiresIn` at execution time and will re-fetch it if necessary. The cache check does not cost much. There is one * to this - we have currently a performance flaw that we fetch destination service tokens even if the cache is hit later on. We have a ticket to do this in a lazy way but this is not yet implemented. 

Best
Frank

**Comment by drvup** [comment]
Hi @FrankEssenberger,

thanks for your response and the provided link to the documentation. By the way, there isn't mentioned anything about the "expiresIn" functionality and if I did debug & read the (compiled) code correctly, the 5 minutes-cache-time is a default value who is taking place, if there is NO expiration time on the authToken object available.

Using the custom interface and the "setDestinationCache()" functionality is indeed a possible solution, thanks again for pointing me to that. I'll give it a try.

Coming back to my origin request about reducing the expiresIn value about some minutes, like it's done by the destination-service, let me try to explain in another example:
- I do fetch the destination from cache. Destination has an expires date set -> expires in 5 seconds
- I save the fetched destination to a const, so I can access it with all requests I am going to send (architecture decission***)
- I fire 10 different requests to the same destination. 
- The first 6 do work, the other 4 do fail due to some (time-delays) and the then expired JWT.

Yes, this is completely on me and the architecture of the application, but I can imagine other devs will run into same situation where they did fetch the destination and saved it to use it multiple times. So I guess follow the approach by the destination-service logic to not throw away the bearer token some minutes before it does expire, could help and is a low-brainer :) 

Thanks for the great support,
Regards,
Cedric

*** Effort of that -> I can manipulate / extend the destination before usage. Think about something like that:
Cornerstonen oAuth V2 does only allow to fetch bearer tokens via post statements by providing specific properties .... whatever, so I can not use the default approach by the SDK (or by the destination-service either). No issue, that's nothing to blame to SAP :D 
So I had to build something to fetch a bearer on my own:
![image](https://user-images.githubusercontent.com/9018930/210973338-902c92cf-4989-4768-b7d4-346a385dd8b7.png)

**Comment by drvup** [comment]
One more thought on that:
I discovered why this is happening quite often with 1 specific app. It's because the app is running an express-route every 12h (via job-scheduler). The JWT token does expire after 12h (xsuaa-default setting).
So at 1am it's running the first time and fetches the destination from the dest-service (some seconds after 1 am). It's caching / saving it locally on the app. The SDK does set the expires-timestamp.
12hours later at 1pm it's running again and uses the destination from the cache. Still valid for some seconds... then it's going to expire while runtime of the route.

And the expiresIn, saved on the destination-cache is still the same value as it was at the time saved on the cache - because the SDK is only dealing with the expires-timestamp.

That's exactly the case my app is running into and does explain the discovered scenario.

**Comment by FrankEssenberger** [comment]
Hi @drvup,

I have been thinking about possible solutions and since the origin is related to the fact, that the destination is hold outside the `execute()` function, only a check before directly before the actual HTTP call would make sense I would say. I guess this could be a great example of a custom middleware. This is wrapped directly around the actual call and you could do the following in your implementation:
- get the validity duration from the auth token header
- If necessary refetch the destination
- replace the token OR execute once more with the newly fetched destination

I have linked a PR where I added the `destinationName` to the context of the middleware so that you can easily do a refetch. This will be available in version 3 also with documentation on the portal.

Best
Frank

**Comment by drvup** [comment]
Hi @FrankEssenberger ,

thanks for your feedback and the provided ability. Looking forward for v3 :) 

Can you please be so kind and add a information [here](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination-cache), the 5 minutes are only relevant if no "expiresIn" is existing!?
Because that's exactly the case and did confuse me in the first iteration (before debugging and identifying how it's done)

Thanks in the name of all documentation-readers and the community (for all the support!)

Regards,
Cedric

**Comment by FrankEssenberger** [comment]
PR for documentation is open.

**Comment by jjtang1985** [comment]
I'll close this issue, as the [middleware feature](https://sap.github.io/cloud-sdk/docs/js/features/middleware) has been released in the SDK v3.
