### ISSUE TITLE
generated package versioning through service mapping file

### ISSUE THREAD

**Issue by geert-janklaps** [SAP/cloud-sdk-js#3526]
**Is your feature request related to a problem? Please describe.**
With the announcement of the discontinuation of the pregenerated clients as of version 3.0, we're looking into creating a mono repository with generated clients which are generated with the generator and deployed to our private package manager to re-use them in our multi-tenant solutions. 
With the service mapping file we're able to perfectly setup the right structure for such mono repository and regenerating the clients in case of updated EDMX files works perfectly fine.

There is however one problem, versioning of the generated package.json file. Everytime the generated package.json file contains the same version 1.0.0. Which becomes problematic when deploying the newly generated version to a package manager.

**Describe the solution you'd like**
The service mapping json file already allows to setup the npm package name. Allowing to set a npm package version would already be a great help to overcome this issue.

Something like:
```json
{
    "API_SALES_QUOTATION_SRV": {
        "directoryName": "sales-quotation-v2",
        "npmPackageName": "@thevaluechain/sales-quotation-v2",
        "npmPackageVersion": "1.0.2"
    }
}
```

Another great feature for the generator would be to automatically bump up the version incase of a re-generated package, but that's less important, allowing full control through the service mapping file would be a great start.

**Describe alternatives you've considered**
Keeping track of versions manually and adapting the generated package.json file after regenerating it. This is off course not efficient when the amount of generated libraries starts to go up. (expected generated clients for current project would be about 20-25)

Affected development phase: Getting Started
Impact: Inconvenience
Timeline: Go-Live is in 16 weeks.

**Additional context**

**Comment by FrankEssenberger** [comment]
Hi @geert-janklaps,

great that you use the SDK and having a private repository to share generated util code is a great idea. In the past we published all the clients and had some flag internally to manage the versions of the npm packages.

However, we decided not to proceed this way because the packages were not heavily used and we did not want to flood npm with so many libraras every quarter. In Java bigger packages are accepted so it was possible to bundle all services. Long story to explain why we discontinued the published clients and wanted to reduce the complexity in the generator. So we cleaned away all the configuration options. The idea is that the rich external tooling from the npm eco system can be used to manage ther versions of multiple packages in a monorepo.

With this said, I am sorry that we will most likely not add this feature in the near future. If we add the version then the next request will appear to configure the licence or scripts or ....

Without doing much research I can tell how we manage the versions in our mono repo:
- Use workspaces (yarn or npm)
- If you keep the package.json we use [changeset](https://github.com/changesets/changesets) - version increases automatically based on changeset files.
- If you do not keep the package.json we use somethig like `npm version 1.2.3 --workspaces` to set the version manually all packages.
- ....

I hope this helps and the inconvenience is not too big.

Best
Frank

**Comment by geert-janklaps** [comment]
Hi @FrankEssenberger,

Thanks for the feedback, with that background I do understand the discontinuation even more.
Thanks for the tips in terms of versioning, I've played around with all of them and I think the changeset option will be a great way to keep track of versioning.

I am at the point where I created a custom cleanup script, leaving only non .js, .ts, .map, tsconfig.json files in each workspace. This bascially means that the package.json & changelog.MD files remain in the folders before the generator runs again. (the clearOutputDir option removes everything, which is what we want to prevent in this case)

There is however one issue I still see, at this point either by using the generateJson or include flags the package.json is always overwritten every time the generator runs with the overwrite option. This messes up the individual versioning of packages.
If the overwrite option is not specified, the generator fails.

A solution I see, would be to add an option to ignore existing files if they exist. Basically allowing all the files to be properly generated, ignoring the existing files.

Another thing I've noticed, when using the include option to copy our own package.json as suggested, the generator doesn't update the package name with the one configured in the service-mapping.json file. Not sure if this is intentional?

Best regards,
Geert-Jan

**Comment by FrankEssenberger** [comment]
Hi Geert-Jan,

we use also the changeset tool in our OS repo which also builds you nice changelog.md files linking the commit with ID to each feature - in your case not so relevant but a useful thing to have. So I think to have to use this is a good choice. Regarding your questions:
- yes with the include it takes the file as is so it will not have the package name. We used this include option for really static content like licence files. So I guess for the package.json is not a good usecase
- If you use the `changeset` tool the package.json files with the version need to stay anyhow so you could only generate everything on the initial run inlcuding the package.json. Then you switch off the `generatePackageJson` flag so it is not written anymore and clean away the generated sources using you cleanup scirpt.
- Regarding the ignore existing files options I think in most cases if a source file is existing but change you would want to replace it. Only for config files this is meaningful I guess.
- Alternatively you could also just delete everything on each generation run and execute a `npm vesrion 1.2.3 --workspaces` to set a specific version after the generation and take this value from your local npm repo (latest published version). If nothing is there the value 1.0.0 from sdk is a good starting point. From my experience to use the repo as single source of truth is not bad because at a certain point you mess up a deployment or a changeset config and just want to clean everything and set the versions to what is actually in the npm repo. This requires a connection to the npm but you need this anyhow for publishing I guess.

**Comment by jjtang1985** [comment]
As @FrankEssenberger shared some alternative, I'll close this ticket.
