### ISSUE TITLE
Calls to destination with certificates lead to "unsupported" issue with Nodejs version > 17

### ISSUE THREAD

**Issue by lgunko** [SAP/cloud-sdk-js#3544]
**Describe the bug**
When destination has certificates set up - cloud sdk adds this certificate to the httpsAgent despite the fact that destination is not using the ClientCertificateAuthentication. This leads to [Axios Response] ERROR MESSAGE: "unsupported" when the legacy ciphers are used (for example SHA-1)

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up the destination with SHA-1 SAML certificate 
2. Execute cloudSdkConnectivity.getDestinationFromDestinationService and executeHttpRequest to this destination
3. See error:
 'unsupported', stack: 'Error: unsupported\\n    at configSecureContext (node:internal/tls/secure-context:277:15)\\n    at Object.createSecureContext (node:_tls_common:117:3)\\n    at Object.connect (node:_tls_wrap:1629:48)\\n    at Agent.createConnection (node:https:150:22)\\n    at Agent.createSocket (node:_http_agent:350:26)\\n    at Agent.addRequest (node:_http_agent:297:10)\\n    at new ClientRequest (node:_http_client:335:16)\\n    at Object.request (node:https:360:10)\\n    at RedirectableRequest._performRequest (/app/node_modules/follow-redirects/index.js:284:24)\\n    at new RedirectableRequest (/app/node_modules/follow-redirects/index.js:66:8)'

**Expected behavior**
destination should be called without adding the certificate to the httpsAgent

**Used Versions:**

- node version via `18.12.1`
- npm version via `9.5.0`
- SAP Cloud SDK version you used as dependency: 2.12.1

**Impact / Priority**
we can not connect to some destinations

Affected development phase: e.g. Production

Impact: e.g. Inconvenience

Timeline: e.g. Go-Live is in 11 weeks.

Issue on Axis side:
https://github.com/axios/axios/issues/4778

**Comment by marikaner** [comment]
Hey @lgunko thank you for reporting this. What authentication type does your destination have?
I wonder why there is a certificate if it not supposed to be used and whether this would occur with other users as well.

**Comment by ptesny** [comment]
Hello, 

Indeed, it seems that sap-cloud-sdk **always** appends anything in the certificates array from the find destination payload  to the axios httpsAgent config; and that despite the fact that my destination is `OAuth2SAMLBearerAssertion` type and not `ClientCertificateAuthentication` type; 
The self-signed x509 certificate in my destination is used to sign the SAML assertion and is not supposed to be used for mTLS; especially that the mTLS certificates should be CA-signed.  For instance, with S/4HANA Cloud when using the x509 client certificate authentication it is a CA-signed x509 certificate with the CA trusted by a given S/4HANA Cloud tenant.

I hope that helps;

**Comment by ptesny** [comment]
> I wonder why there is a certificate if it not supposed to be used and whether this would occur with other users as well.

it seems that with nodejs version <=16 the issue was hidden; only starting with nodejs versions 17 and above the issue started to be visible; 
Regardless, if anyone wants to be using mTLS with the BTP destinations it the destination service offers either a dedicated `ClientCertificateAuthentication` authentication type or/and there is a way to add the mTLS CA-signed certificate in a given destination definition properties; 
I hope that helps;

**Comment by fwilhe** [comment]
Hi @lgunko 

how did you set up the destination? In the BTP ui the options for destinations change based on the type, so if you're not selecting ClientCertificateAuthentication you won't be able to select a certificate for that destination.

Or are you referring to the right side of that screen where you can select a trust store?

<img width="1429" alt="Screenshot 2023-02-21 at 11 23 22" src="https://user-images.githubusercontent.com/2292245/220318322-93119b8c-f3f8-4bbf-a4f2-34863de104fc.png">

Can you describe in more detail how your setup can be reproduced?

Also is there a specific reason you you'll need to use legacy certificates? There are reasons why newer node versions don't support using legacy certificates.

**Comment by ptesny** [comment]
Hello, this is for `OAuth2SAMLBearerAssertion` destinations (there is no mTLS); I hope that helps;

**Comment by fwilhe** [comment]
I've tried it out with a `OAuth2SAMLBearerAssertion` Destination.

I'm calling the `getDestination` function with that destination's name as an argument.

With the 'Use default JDK truststore' option checked I get a destination object where the `certificates` field is an empty array.

When I uncheck that checkbox and select a given cert, and do the same call again, I get a destination object where the `certificates` field is a list with the name of the cert I selected before.

I can't see any bug here. Did I get it wrong? Can you describe in more detail what the actual and the expected behaviour is?

**Comment by marikaner** [comment]
Hey @ptesny and @lgunko, I am happy to announce that we fixed this issue yesterday. It is fixed in both version 2 and the freshly released version 3. My recommendation is to try it with version 2 first and then switch to version 3.
