### ISSUE TITLE
What are the benefits to upgrade from v2 to v3

### ISSUE THREAD

**Issue by 1993hzh** [SAP/cloud-sdk-js#3858]
Hi all,

We are using @sap-cloud-sdk version 2 in our applications, and we received warning log to recommend us to upgrade to version 3.
I am always interested in catching up with latest stable version, but I need some strong reasons to convince my teammates that we should upgrade. However, after go through the upgrade guide, I didn't find any content regarding why we should upgrade to version 3, it's definitely not convincible just because v2 is no longer actively maintained, can you guys kindly help give some benefits? (and I do think add `WHY` section in upgrade guide is really helpful)

**Comment by tomfrenken** [comment]
Hi @1993hzh,

thank you for your feedback, I agree that we should add a `WHY` section to our upgrade guide and will bring this up to the team.

Here is a rough list of benefits for upgrading to version 3.

1) First and foremost: Our new [resilience package](https://sap.github.io/cloud-sdk/docs/js/guides/resilience), which enables you to build different resilience middlewares into your application with ease
2) Support for the latest node LTS version
3) Aligned APIs between our odata and openapi clients and generators
4) A cleaner API, meaning better documentation, naming of variables, and removal of redundant functionality
5) Last but not least, our support in case you face issues or find bugs in the future

**Comment by jjtang1985** [comment]
I would add one more point to @tomfrenken 's list:
- dependency updates, which helps reduce the risks of vulnerabilities. Of course, as a consumer, you can also manage transitive dependencies by your own, but some users prefer centralised fix (security incident) instead of doing it by their own.

Please check our release policy [here](https://sap.github.io/cloud-sdk/docs/js/release-policy#fixes-and-maintenance).
