### ISSUE TITLE
Export "resolveServiceBinding()" within "@sap-cloud-sdk/connectivity" by default

### ISSUE THREAD

**Issue by drvup** [SAP/cloud-sdk-js#3903]
Hey SDK-Js team,

I had to debug an incident on our landscape, within multiple nodeJs apps, using your wonderful SDK. This saves so much time and effort, thanks once more again :D 

Whatever, I've designed a package to handle interactions with the SAP Jobscheduler Service. Therefore, I am using capabilities of `@sap-cloud-sdk/connectivity`. Unfortunately, with version 3.2.0 you did rename `resolveService()` to `resolveServiceBinding()` and this change was not reflected on our site. So the jobs on our end did stuck. 
However, as this is "just" exported by your "internal" functions, I do not want to blame someone ;-) 

Instead, I want to ask you to add this nice capability to the default exports of the connectivity-package. 
I do use the function to get environment variables via the "VCAP_SERVICES". You're doing that within the `xsenv` package. Of course, I can do the same on my site and make it stable. But why do so if this great small piece of code could be useful for everyone. 

So that's my request: Please add `resolveServiceBinding()` to the exports of `@sap-cloud-sdk/connectivity`.

Thanks,
Kind regards,
Cedric

**Is your feature request related to a problem? Please describe.**
No, related to an incident who did occur on our end.

**Impact / Priority**
low

Affected development phase:
Production environment

Impact: e.g. 
No Impact

**Comment by marikaner** [comment]
Hey @drvup,

thank you for your kind words. We have discussed this internally and have a few questions/points, that we would like to put out there before making decisions. 

1. From our point of view, exposing `resolveServiceBinding()` only makes sense if we also expose `getServiceBinding()`. We could however expose `get...()` only without `resolve...()`. Can you explain, whether your use case requires the additional functionality of `resolve...()` or would `get...()` suffice?
2. We are not too keen to expose those functions publicly as part of the connectivity package, because it defocusses the scope of the package. When we expose one of the service bindings utility functions, it opens the door to expose some more functions, e.g. `getServiceBindingByInstanceName()` or `getServiceBindings()`.
We think the API would be cleaner, if we exposed this in a separate package. However, this would introduce additional complexity, that we don't think is currently justified...

Given the circumstances, do you think that it would be worth exposing the function anyways?
Maybe it would be an option for you to use the internal function + wrapping a test around it to ensure it behaves the way you expect instead?

**Comment by drvup** [comment]
Hi @marikaner ,
thanks for coming back to me!

Yes, I am with you and the fact that it does only make sense, to expose both functionalities as the `resolve..()` does rely on the `get..()`. So yes, I am with you on that. The `get..()` functionality would be enough for my situation.
Back in time, I did debug another package where I did identify it was using the `resolve..()` one. So from my POV, I do not take care ;-) 

About part 2:
I am also with you, that you're thinking about what you do expose where. Also, I do understand, why you struggle with enabling `getServiceBindings()` within the connectivity package - BUT to be realistic; it's about connectivity. I mean, it's just a credential-share thing, and you do resolve the service data from the environment credentials. Okay, so it's not directly for connectivity, but within the result of that, I definitely need to make a connection to the service(-url) - so back with that, it's connectivity. 

The other idea from my POV:
Make it a connectivity thing only :) 
So instead letting me `resolve..()` or `get..()` and within, faking some kind of destination like this sample:

```
// Fetch the credentials from environment variables
const service = sdkConnectivityInt.resolveServiceBinding('jobscheduler');

// Prepare our job-scheduler-fake-destination
this.destination = {
    url: service.credentials.url + '/scheduler',
    authentication: 'OAuth2ClientCredentials',
    type: 'HTTP',
    name: 'FakeJSDestination',
    proxyType: 'Internet',
    clientId: service.credentials.uaa.clientid,
    clientSecret: service.credentials.uaa.clientsecret,
    tokenServiceUrl: service.credentials.url + '/oauth/token?grant_type=client_credentials',
};
```

You could provide something like `createDestinationForService(name):HttpDestination` :) 
Then it's 100% about connectivity :D 

Wrapping it up;
I do get your point by not exposing it within the package, but maybe you'll get my point why it could be still useful for use-cases, who are not out-of-the-box-destination ones :-) 

Let me know what you're thinking about my approach,
BR,
Cedric

**Comment by drvup** [comment]
Nice!
Thanks for letting me know. I will check that next week and let you know. If it suits the case, I will update the documentation accordingly;-)

BR,
Cedric
