### ISSUE TITLE
Support sending E-Mail Using a Microsoft Graph destination

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-sdk-js#4002]
**Describe the solution you'd like**

Right now the [Mail Client](https://sap.github.io/cloud-sdk/docs/js/features/mail-client) functionality covers sending E-Mail to Destinations of Type MAIL. But as for example Microsoft doesn't support SMTP anymore the Microsoft Graph needs to be used. I would like to request support for Microsoft Graph in the SAP Cloud SDK to implement only against one API instead of every developer at SAP, SAP Partners or Customers with the need to support SMTP and Microsoft Graph in the same SaaS application to maintain two options.

**Describe alternatives you've considered**

Right now every Application that should support SMTP and Microsoft Graph needs to implement both options and needs to provide configuration options which implementation needs to be used. Also the SAP Product SAP Enterprise Product Development describes the configuration for:

- [Destination for Email Notifications Using SMTP APIs](https://help.sap.com/docs/PLM_EPD/1bfdb8b2f0264b66a818a2a889ee8c31/a5b4fdc9252d4f9183289cc594447e9a.html?locale=en-US)
- [Destination for Email Notifications Using Microsoft Graph](https://help.sap.com/docs/PLM_EPD/1bfdb8b2f0264b66a818a2a889ee8c31/f2efadbbd4344414a449d50cedc98b87.html?locale=en-US)

if SAP Cloud SDK would provide a common interface this could be simplified.

**Impact / Priority**

Affected development phase: Development

Impact: Inconvenience

**Comment by marikaner** [comment]
Hey @gregorwolf, thank you for the suggestion. As I don't have much experience with sending e-mails through Microsoft Graph, I would like to better understand, what exactly you would envision in the SAP Cloud SDK.
The documentation you shared only shows how to configure the destination. This destination would be of type `HTTP` which you can already retrieve with `getDestination()` as of today. However, I assume you would like to use `sendMail()` with a destination of type `HTTP` to then send an e-mail using HTTP instead of SMTP. Is my understanding correct?

Building such a feature would require quite a bit of research and discussion and I don't think this is realistic in the near future (unless there is a high demand for this).

I found this [sample](https://github.com/SAP-samples/btp-cf-cap-multitenant-susaas/blob/main/docu/4-expert/send-emails-graph-api/code/index.js), that shows how to send an e-mail using MS Graph. I think for most use cases it should be quite straight forward to include the information of a destination in this code with the help of the SDK by using:
1. [buildHttpRequest](https://sap.github.io/cloud-sdk/api/v3/functions/sap_cloud_sdk_http_client.buildHttpRequest.html) to get URL, headers and query parameters for the request.
2. [getDestination](https://sap.github.io/cloud-sdk/api/v3/functions/sap_cloud_sdk_connectivity.getDestination.html) to access the additional properties of the destination through [`originalProperties`](https://sap.github.io/cloud-sdk/api/v3/interfaces/sap_cloud_sdk_connectivity.Destination.html#originalProperties).

Let me know if this helps.

**Comment by ThomasSwolfs** [comment]
@gregorwolf nice idea! A SendGrid connection would also be very welcome.

**Comment by mr-flannery** [comment]
I will close this issue due to inactivity. If this is still relevant, please reopen it and continue the discussion.

Best regards,
Dennis
