### ISSUE TITLE
How to avoid warning: The provided JWT payload does not include a 'zid' property.

### ISSUE THREAD

**Issue by hosssa** [SAP/cloud-sdk-js#4198]
We are successfully performing an executeHttpRequest via BTP destination. 

```js
executeHttpRequest(
    { 
      destinationName: "NAME",
      useCache: true
    },
    requestConfig
)
```

However, we constantly get the following warning, which fills up our logs:

`(jwt): Warning JWT: The provided JWT payload does not include a 'zid' property.`

How can we avoid this warning? Is there a way to disable it?

**Comment by marikaner** [comment]
Hey @hosssa, thanks for bringing that up. Does this occur when use disable the cache with `useCache: false`?
I believe this warning occurs because you are using the cache. By default the cache is isolated by user and tenant. As you don't pass a JWT, there is no tenant information, so that the destination cannot be safely cached with the given isolation. You are probably also seeing a second warning shortly after: `Could not build destination cache key. Isolation strategy 'tenant-user' is used, but tenant id or user id is undefined in JWT.`, right?

I might be wrong though, so let me know if you see the other warning as well. I will take a closer look at this tomorrow.

**Comment by nocin** [comment]
Hi,

the messages also occurs with `useCache: false`. Also, there is no second warning after it. 
![grafik](https://github.com/SAP/cloud-sdk-js/assets/35531968/be2fe373-48fd-4020-8512-f98a4007656b)

I'm testing locally in BAS with a destination setup in a .env file and without multitenancy. 

BR, Nico

**Comment by marikaner** [comment]
Hey @hosssa, I am working on improving the warning, it is quite misleading.

For your other request: The default isolation strategy is "tenant-user" if you pass a token that has a `user_id`. If you pass no token or a token without user ID, the strategy is `tenant`. If you don't have multitenancy, you basically have only one tenant - so it is a special case of isolation strategy "tenant".
If you don't pass a JWT, the SDK retrieves the subaccount ID and uses this as the tenant and assumes isolation strategy "tenant" => this is also why you don't see the second error message that I erroneously expected.
Did you have issues with caching or did I just confuse you with my previous message?

**Comment by hosssa** [comment]
Hi @marikaner, 

Thanks for the details about the caching mechanism. I assume caching works fine, as the first request throws 2 'zid' warning messages but subsequent requests only one.

**Comment by marikaner** [comment]
I opened a PR to remove the logs alltogether, I currently don't see a good reason to keep them. We will soon release a new version to include this, stay tuned ;)
