### ISSUE TITLE
I am getting 404 error

### ISSUE THREAD

**Issue by SyedBabaTajuddinHussaini** [SAP/cloud-sdk-js#4285]
Hi,

I tried to use the SAP Cloud SDK in my SAP CAP application to send an email using destinations in SAP BTP. However, I am encountering the below issue. Kindly guide.

Please find attached herewith the screenshots of code snippets.

![maildotcds](https://github.com/SAP/cloud-sdk-js/assets/37118657/ad0782e1-1b73-4f1b-8da7-a696ddc31457)
![maildotjs](https://github.com/SAP/cloud-sdk-js/assets/37118657/e3c11a76-5d6e-4d20-a40e-b6ad5a536279)
![response](https://github.com/SAP/cloud-sdk-js/assets/37118657/4fd406ac-3d66-43e7-bd5d-904b0b84dddc)
![testdothttp](https://github.com/SAP/cloud-sdk-js/assets/37118657/911dc1f9-8d15-488a-b2f8-7b3dc3d7a351)

Please assist in this regard at an earliest.

Regards,
Syed

**Comment by marikaner** [comment]
Hey @SyedBabaTajuddinHussaini,

it seems that the 404 comes from your app because you cannot POST against `/mail/sendMail`. Is there an actual error from the SAP Cloud SDK? I might be wrong but from the logs you shared it even looks like the `sendMail()` function is never reached. Could you check this and share a few more details?

**Comment by SyedBabaTajuddinHussaini** [comment]
Hi @marikaner,
You were correct. The issue has been fixed.
Thank you.
