### ISSUE TITLE
Access Remote Service using Cloud SDK+AMS(Authorization Management Service)

### ISSUE THREAD

**Issue by gopalanand333** [SAP/cloud-sdk-js#4343]
**Is your feature request related to a problem? Please describe.**
As part of the project, I plan to implement Remote system connectivity using CAP+Cloud SDK+ authentication using AMS(Authorization Management Service). 
When accessing the remote system, I get the error: `Failed to load destination. Caused by: Could not find binding to the XSUAA service.` 
As the goal is to use IAS+AMS for authentication and authorization, we don't use XSUAA and we are looking for a way to have a Remote system call. 

**Describe the solution you'd like**
I want to access remote systems like S/4HANA using SAP Cloud SDK, secured by AMS and IAS.

**Describe alternatives you've considered**
I have tried CAP with could SDK, getting a similar result. 

**Impact / Priority**

Affected development 

Impact:  Blocked

Timeline: Sooner the better 

**Additional context**
I am trying the BTP Developer Guide, where I have implemented AMS and not using it to connect with the Remote S/4HANA system.  https://discovery-center.cloud.sap/missiondetail/4327/4608/?tab=projectboard
<img width="1410" alt="image" src="https://github.com/SAP/cloud-sdk-js/assets/32189444/d933408c-af7c-4f97-b124-618c335e6b4c">

**Comment by mr-flannery** [comment]
Hi @gopalanand333 , sorry for taking some time to reply.

Your error is likely caused by the SDK by default trying to exchange IAS tokens for XSUAA tokens. This has been implemented because in the past many service were unable to handle IAS tokens. You can disable this behavior when fetching destinations as documented [here](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#destination-fetch-options). when using CAP, you may need to configure this in the CDS settings under `destinationOptions` (see [docs](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#destination-fetch-options)).

Hopefully this will unblock you. Please be aware that we not (yet) run any tests with the SDK + AMS. I believe this should be sufficient, since, beyond this specific point, AMS should not concern any other SDK functionality. However, since we haven't tested or documented it, this is the best I can currently tell you.

If this doesn't work, please reach out again.

**Comment by gopalanand333** [comment]
@mr-flannery  
thanks for replying, This approach destinationOptions (see [docs](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#destination-fetch-options)) works as expected. 
It would be great if SDK mentions also for non-CAP-based implementation.

**Comment by mr-flannery** [comment]
Hi @gopalanand333 ,

happy to hear it worked! 

> It would be great if SDK mentions also for non-CAP-based implementation.

I'm a little confused. The docs you linked are the place where it's documented for non-CAP-based implementations. Do you think something is missing on that page?

**Comment by mr-flannery** [comment]
Hi @gopalanand333 , I'm closing this ticket since we haven't heard back from you in 5 weeks.
