### ISSUE TITLE
Wrong URI Encoding after upgrade from 3.11.0 to Version 3.12.0

### ISSUE THREAD

**Issue by chuckberrry** [SAP/cloud-sdk-js#4500]
**Describe the bug**
It seems that the URI encoding is not working properly after the upgrade from version 3.11.0 to version 3.12.0.
There is a kind of double encoding that causes an error in the CAP application.

**To Reproduce**

1. Set up ...
Use Cloud SDK Version 3.12.0 and implement a simple request that contains a filter, e.g.

```
response = await serviceApi
        .requestBuilder()
        .getAll()
        .filter(
            serviceApi.schema.CODE.equals(code),
            serviceApi.schema.TYPE.equals(type),
            )
        .top(1)
        .execute(this.destination);
```
2. Execute ...
The coding should execute an HTTP request.
3. Confirm ...
The Request will look similar to this:
GET /odata/v4/service/Entity?%24filter=(code%2520eq%2520'1111'%2520and%2520type%2520eq%2520'GL')&%24top=1
As you can see, the URI encoding is not correct and causes an 400 Bad request in the CAP Application:
{"code":"400","message":"Expected uri token 'CLOSE' could not be found in '(code%20eq%20'1111'%20and%20type%20eq%20'GL')'

It looks as if the filter has been encoded twice.

**Expected behavior**
In Cloud SDK Version 3.11.0 the URI is correct and looks like this:
GET /odata/v4/service/Entity?%24filter=(code%20eq%20'1111'%20and%20type%20eq%20'GL')&%24top=1

**Used Versions:**
Works in Version 3.11.0, Error in Version 3.12.0

- node version via `node -v`
v18.18.0
- npm version via `npm -v`
9.8.1
- SAP Cloud SDK version you used as dependency
3.12.0

**Comment by marikaner** [comment]
Can you please make sure that all your SDK dependencies are really upgraded to version 3.12. To make absolutely sure, please remove your `node_modules` and install again.

**Comment by chuckberrry** [comment]
Same behavior after removing the node_modules and reinstalling

**Comment by marikaner** [comment]
Did you also upgrade the version in your client? This is important because the SDK is not compatible with itself throughout minor versions. In this particular case we adjusted an internal function that is responsible for the encoding - the behavior did not change, though.
The problem that you describe should only occur if you have two dependencies to the SAP Cloud SDK, e.g. `@sap-cloud-sdk/http-client` and `@sap-cloud-sdk/odata-v4` and one of them points to `3.11.X` and the other to `3.12.X`.

Could you please confirm that this is NOT what it causing your issue? And if it is not could you please describe your setup in a bit more detail, e.g. does the generated have it's own `package.json` (it should use the same version there as well)? Then we will try to reproduce this.

**Comment by chuckberrry** [comment]
you were right, we had other dependencies to an older version of `@sap-cloud-sdk/odata-v4`.
Thank you for your quick reply
