### ISSUE TITLE
Authentication type OAuth2UserTokenExchange is not supported in function getAuthenticationRelatedHeaders in /packages/core/src/connectivity/scp-cf/authorization-header.ts

### ISSUE THREAD

**Issue by blaart** [SAP/cloud-sdk-js#817]
In one of our destinations we use the OAuth2UserTokenExchange authentication type. Unfortunately this type is not yet supported in the getAuthenticationRelatedHeaders function in /packages/core/src/connectivity/scp-cf/authorization-header.ts which results in an error. 

We really like to use the sdk for resolving our destinations, for that we need to have support for this authentication type. Can you please fix that?

**Comment by blaart** [comment]
Never mind, this will be fixed in https://github.com/SAP/cloud-sdk-js/pull/792

**Comment by FrankEssenberger** [comment]
Hello @blaart,

yes we are currently working on this feature. But it was good that you opened the issue because I forgot to parse the destination service authToken result in the `getAuthenticationRelatedHeaders` method you mentioned. Just a few lines and we would have seen it in the E2E tests before publishing but this way it is quicker.

Best
Frank

**Comment by blaart** [comment]
Hi Frank, Thanks for your reply. I was looking into the branch and wondered that too. When ready I'm happy to give this a try in the field. 
Kind regards,
Peter

**Comment by FrankEssenberger** [comment]
I was actually hoping that the handling is done generically from the moment the destination is received but this is not the case as I learned.
