### ISSUE TITLE
using a destination with authentication type OAuth2ClientCredentials does not use the defined scope (which is required)

### ISSUE THREAD

**Issue by blaart** [SAP/cloud-sdk-js#870]
We are using a token server of Microsoft for a user token grant request.
the url is like: https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token

See also https://github.com/SAP/cloud-sdk-js/issues/816

As 816 is solved I now can test the call to microsoft, but receive an error as the scope is required. scope in my case is defined in the destination as an additional parameter. it should be added in the body (like grant_type, client_id en client_secret, which  are indeed already filled).

**Comment by jjtang1985** [comment]
Hi @blaart , I assume you are using the `additional properties` from the CF for your `additional parameters` in the request body. Could you please confirm that you are using the `scope` as an additional property saved in the destination on the CF and the the mandatory parameter is also called `scope` that you need in the request body? Of course, this should be considered as general issue instead of a specific key.

**Comment by blaart** [comment]
Hi @jjtang1985, you are correct, we use an additional property in the CF destination. Both the CF additional property and the parameter in the body are specified as 'scope'

**Comment by jjtang1985** [comment]
Thank you @blaart for your quick answer. I'll let you know once there are some updates.

**Comment by FrankEssenberger** [comment]
Hello and happy new year,

I investigated the issue a bit and I will post my findings here so that we have all information together.

I directly found an suboptimal coding that for the `OAuth2ClientCredentials` flow the  find destination endpoint is not triggered. Only this call to the destination service will trigger the OAuth flow and lead to a destination with the `authToken` property filled with the access token see [here](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/4e1d742a3d45472d83b411e141729795.html). Currently the returned destination has no authToken and later when we build the header the token is added by [hand](https://github.com/SAP/cloud-sdk-js/blob/6063f24ad0aa2cea0c1de98876045a2a4cd0177f/packages/core/src/connectivity/scp-cf/authorization-header.ts#L246)

I was able to reproduce the bug locally and we should add one more case [here](https://github.com/SAP/cloud-sdk-js/blob/feed4c0b8d81676bcd30e0b8eb93615108a23fbe/packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts#L99) to let the destination service handle  the `OAuth2ClientCredentials` for us. Since the `scope` variable is listed in the destination properties in the [description](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/4e1d742a3d45472d83b411e141729795.html) I would hope that the destination service then considers this scope.

I will give you an update once we have change the code.

Best
Frank

**Comment by FrankEssenberger** [comment]
So the initial idea to fix it has been merged. I hope this solves the issue.

**Comment by blaart** [comment]
Hi Frank, it certainly did, I have tested all use cases we have for now and it works fine, thanks for fixing!

**Comment by jiangxin0503** [comment]
> Hello and happy new year,
> 
> I investigated the issue a bit and I will post my findings here so that we have all information together.
> 
> I directly found an suboptimal coding that for the `OAuth2ClientCredentials` flow the find destination endpoint is not triggered. Only this call to the destination service will trigger the OAuth flow and lead to a destination with the `authToken` property filled with the access token see [here](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/4e1d742a3d45472d83b411e141729795.html). Currently the returned destination has no authToken and later when we build the header the token is added by [hand](https://github.com/SAP/cloud-sdk-js/blob/6063f24ad0aa2cea0c1de98876045a2a4cd0177f/packages/core/src/connectivity/scp-cf/authorization-header.ts#L246)
> 
> I was able to reproduce the bug locally and we should add one more case [here](https://github.com/SAP/cloud-sdk-js/blob/feed4c0b8d81676bcd30e0b8eb93615108a23fbe/packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts#L99) to let the destination service handle the `OAuth2ClientCredentials` for us. Since the `scope` variable is listed in the destination properties in the [description](https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/4e1d742a3d45472d83b411e141729795.html) I would hope that the destination service then considers this scope.
> 
> I will give you an update once we have change the code.
> 
> Best
> Frank

Hi @FrankEssenberger ,

This issue is fixed in version 1.36.1. but in version 1.37.0.  The issue is still there. 

See the code here: https://github.com/SAP/cloud-sdk-js/blob/v1.37.0/packages/core/src/connectivity/scp-cf/authorization-header.ts#L225-L229 

Can you please kindly double check as we are facing this issue in the latest version.

Thanks,
Regards,
Xin

**Comment by FrankEssenberger** [comment]
@jiangxin0503 When I look at the code for version 1.36.1 and 1.37.0 the change that all `OAuth` cases are handled in the same switch case:
```
 case 'OAuth2SAMLBearerAssertion':
    case 'OAuth2UserTokenExchange':
    case 'OAuth2ClientCredentials':
      return headerFromTokens(
        destination.authentication,
        destination.authTokens
      );
```
is present in version 1.37.0 and not in verison 1.36.1. This is intended then in the [destiantion-from-service](https://github.com/SAP/cloud-sdk-js/blob/f9ad1fc1323f84c9b261e4cbf8bc2953c9a8f71d/packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts#L112-L114) also for the `OAuth2ClientCredentials` a call to the destination service is added and the destination services add the auth token headers. 

Also from a timeline of events I see that the code in version 1.36.1 is the one which is unchanged since many weeks. Then after the release of 1.36.1 I made the change to fix the issue which was then published in version 1.37.0. Could you perhaps check in your node modules if there are perhaps multiple versions of core flying around and perhaps and older version is loaded at runtime?

Best
Frank

**Comment by jiangxin0503** [comment]
Hi @FrankEssenberger ,

If the destination is maintained in the destination service, then it works fine, because the auth  token will be fetched from the code  [destiantion-from-service ](https://github.com/SAP/cloud-sdk-js/blob/f9ad1fc1323f84c9b261e4cbf8bc2953c9a8f71d/packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts#L112-L114)

This is fine, but in my case, i just maintained the destination in my own code, not from the destiantion service.
code like below:

```
  const destination = parseDestination({
    URL: `${URI}`,
    ProxyType: 'Internet',
    Authentication: 'OAuth2ClientCredentials',
    tokenServiceURL: `${tenantUaaUrl}/oauth/token`,
    clientId: `${serviceClientId}`,
    clientSecret: `${serviceClientSecret}`,
    Type: 'HTTP',
  });

  const { data: repoData } = await executeHttpRequest(destination, {
    url: '/rest/v2/test',
    method: 'GET',
  });

```

In this case, i hope that the destination here can also be worked. The token can be fetched in the cloud-sdk, otherwise, we will always send another request to get the token. 
And  in version 1.36.1 it works, but the version 1.37.0 not works.

Best Regards,
Xin

**Comment by FrankEssenberger** [comment]
Hello Xin,

ah ok, now I get the problem. The reason it worked before is that we constructed the headers later, after the destination has been fetched. The problem was that with the old flow we can not consider the scope properly, because the scope is a destination property. Also it is better to let the destination service take care of the token fetching and just take the result instead of reimplementing logic from the destination service.

In your case you could do the following:
- Have a look at the `import { getOAuth2ClientCredentialsToken } from './client-credentials-token';` method and use it to fetch the token and put the result in the `AuthToken` property of the destination or directly in the headers as you like. So you do the same which the SDK has done in version 1.36.1.
- Or you maintain the destinations in the destination service? Is there a specific reason that you want to define the destination in your code?

Best
Frank

**Comment by jiangxin0503** [comment]
Hi @FrankEssenberger ,

Thanks for your information.
And in my case we can try your two solutions, but there are some questions before i have a try: 

- use the method `import { getOAuth2ClientCredentialsToken } from './client-credentials-token'` . But there is comments in the source code with `TODO This should be moved down to the token accessor `
you can see 
```
// TODO: This should be moved down to the token accessor
/**
 * Retrieves an access token required for "OAuth2ClientCredentials" destination authentication type.
 *
 * @param destination - A destination having `OAuth2ClientCredentials` authentication type
 * @returns A promise returning the requested access token on success.
 */
export async function getOAuth2ClientCredentialsToken(
  destination: Destination
): Promise<ClientCredentialsResponse> {
  if (!areValidCredentials(destination)) {
    throw Error(
      'The provided destination does not comply to "OAuth2ClientCredentials" authentication requirements. ' +
        'Check whether the destination includes "tokenServiceUrl", "clientId" and "clientSecret" attributes.'
    );
  }

```
So my questions is that :  will this method  be obseleted in the future release? if this is the case, then i think we can not go this approach.

- Why we do not want to maintain this in destination, firstly, this need manually added in destination. and secondly, in our case the `tokenServiceURL` would be different for different saas tenant, for example, the `tokenServiceURL` would like this `https://{sassSubdomain}/landscape/oauth/token`.  Can we maintain the placeholer(sassSubdomain) in `tokenServiceURL` in destination service. And replace the placeholer(sassSubdomain) programing before calling this destintion ?


Thanks for your help.

Best Regards,
Xin

**Comment by FrankEssenberger** [comment]
Regarding your first point. If a method is exported for a major version 1.X.Y it will stay available in this major version. If we remove something it was an error from our side (breaking change) and please raise an issue. Only in a new major version e.g. 2.X.Y methods may disappear. But we try to add the `deprecated` annotation for a while to the method in the lower major version so that you get warning. 

Regarding you second point I am not 100% sure if this could fix all your needs, but the destination service supports a {tenant} placeholder: https://help.sap.com/viewer/cca91383641e40ffbe03bdc78f00f681/Cloud/en-US/e3c333f9de6245fca326993f2397c13a.html
This should replace the value for a multi tenant application for you.
