### ISSUE TITLE
Debugging project in SAP Business Application Studio

### ISSUE THREAD

**Issue by stefania-santimbrean** [SAP/cloud-sdk-js#990]
Hello,

I created an app using `sap-cloud-sdk init` and developed it using Visual Studio Code. During the development I debugged the app by using the JavaScript Debug Terminal available in VSCode.

I am currently exploring running the app in **Business Application Studio**. Running it normally in a Terminal with `npm run start:dev` works fine in BAS. I haven't found a JavaScript Debug Terminal available, so I tried to configure a `launch.json` file.

In VSCode the following debugging configuration works perfectly, but in BAS it gets stuck in the preLaunchTask:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Debug App",
            "program": "${workspaceFolder}/src/main.ts",
            "preLaunchTask": "tsc: build - tsconfig.json",
            "outFiles": [
                "${workspaceFolder}/dist/**/*.js"
            ],
            "envFile": "${workspaceFolder}/.env",
            "console": "integratedTerminal"
        }
    ]
}
```

So my first question is if you recommend a different way of debugging using launch.json file? And my second one is if projects generated with sap-cloud-sdk are compatible with Business Application Studio?

If you can point me to some examples/documentation on this topic, it would be greatly appreciated also.

Thank you,
Stefania

**Comment by jjtang1985** [comment]
Hi @stefania-santimbrean ,

here is the [documentation](https://sap.github.io/cloud-sdk/docs/js/guides/bas-external-system) that might help.

Best regards,

Junjie

**Comment by stefania-santimbrean** [comment]
Hello @jjtang1985 ,

Thanks so much for your quick response and the documentation. I tried the `launch.json` from the docs in VSCode works perfectly, in BAS the app does not start.

Do you happen to know if the dev space from BAS has anything to do with this? Should I have one particular type of dev space? Or if I need any type of extension?

I appreciate the support,
Thank you,
Stefania

**Comment by jjtang1985** [comment]
Hi @stefania-santimbrean ,

I forwarded your question to my sdk colleagues.
However, since this is a BAS specific question, I'm not sure whether we are able to answer.

Here is the [support platform](https://community.sap.com/search/?ct=qa&mt=67837800100800007077&q=business%20application%20studio&qt=all) of BAS and the [homepage](https://help.sap.com/viewer/product/SAP%20Business%20Application%20Studio/Cloud/en-US).

Best regards,
Junjie

**Comment by stefania-santimbrean** [comment]
Hello @jjtang1985 ,

Thanks for your response! I will close the issue and address it on BAS support!

Kind regards,
Stefania

**Comment by FrankEssenberger** [comment]
Hello @stefania-santimbrean,

I had also a quick look and since it is working in VSC it must be some difference in the BAS which is based on [eclipse theia](https://theia-ide.org/) which is like the open source variant of VSC.

I found also some issue in their repo: https://github.com/eclipse-theia/theia/issues/8930 regarding the `preLaunchTask`. So I would try the following:

- Make a very simple hello world app
-  Do all the prelaunch tasks manually
- See if it starts in the BAS
- If so try to add things like a `npm build` in the preLaunch and then the TS one
- If you experience errors ask the BAS colleagues for their support.

Best
Frank

P.S.: From the [BAS docu](https://help.sap.com/viewer/9d1db9835307451daa8c930fbd9ab264/Cloud/en-US/149f285d410642c291855258aa13a46d.html) the dev space should be no problem. It is even listed at `Prerequisites`.
